#
# Copyright (c) 2014 10X Genomics, Inc. All rights reserved.
#

"""Sample index mappings."""

import sys

# pylint: disable=too-many-lines,invalid-name

# GemCode Tubes
SI_001 = ["TCGCCATA", "GTATACAC", "AATGGTGG", "CGCATGCT"]
SI_002 = ["TATCCTCG", "GCGAGGTC", "CGCTTCAA", "ATAGAAGT"]
SI_003 = ["TGACGTCG", "CTTGTGTA", "ACGACCGT", "GACTAAAC"]
SI_004 = ["ATCTAGCT", "GAGCGTAC", "TCAGCCTG", "CGTATAGA"]
SI_005 = ["CCGTTCCC", "ATACAGTT", "TGTAGTAA", "GACGCAGG"]
SI_006 = ["TCAATTGG", "AGTTAGAA", "GAGCGCTT", "CTCGCACC"]
SI_007 = ["CTGCCTTG", "ACTAGCCC", "GGCTAGAT", "TAAGTAGA"]
SI_008 = ["GGCAGAAA", "ACGGTTCT", "CATTCGTC", "TTACACGG"]
# GemCode Plate
SI_P01_A1 = ["TTGTAAGA", "GGCGTTTC", "CCTACCAT", "AAACGGCG"]
SI_P01_B1 = ["CTAGCTGT", "GCCAACAA", "AGGCTACC", "TATTGGTG"]
SI_P01_C1 = ["GATGCAGT", "AGACTTTC", "TTCTACAG", "CCGAGGCA"]
SI_P01_D1 = ["AGCTGCGT", "GTGGAGCA", "TCTATTAG", "CAACCATC"]
SI_P01_E1 = ["CGCCCGTA", "GTTTGCCT", "TAAGTTAG", "ACGAAAGC"]
SI_P01_F1 = ["TGACTAGT", "GATAGGTA", "CCGTACAG", "ATCGCTCC"]
SI_P01_G1 = ["CATATGCG", "ATGCGATT", "TCCGCTAC", "GGATACGA"]
SI_P01_H1 = ["TCTTGTCC", "CGGGAGTA", "GTCACAGG", "AAACTCAT"]
SI_P01_A2 = ["AGCCCTTT", "TCTTAGGC", "GTGAGAAG", "CAAGTCCA"]
SI_P01_B2 = ["GGTCGAGC", "TTAGATTG", "CCCACCCA", "AAGTTGAT"]
SI_P01_C2 = ["CCGAGAAC", "TGCTCTGT", "GTAGTGCG", "AATCACTA"]
SI_P01_D2 = ["ACATTCCG", "GACACAAT", "CTGCGGTA", "TGTGATGC"]
SI_P01_E2 = ["TCATCAAG", "GTTGGTCC", "AGGCTGGT", "CACAACTA"]
SI_P01_F2 = ["TGCCCGCT", "GCAAACGC", "CATTGATA", "ATGGTTAG"]
SI_P01_G2 = ["CGGTGAGC", "ATAACCTA", "TCCGAGCG", "GATCTTAT"]
SI_P01_H2 = ["CCGAACTC", "AACGGTCA", "TTATTGGT", "GGTCCAAG"]
SI_P01_A3 = ["AAAGCATA", "GCCTTTAT", "CTGCAGCC", "TGTAGCGG"]
SI_P01_B3 = ["TCATCCTT", "ATTGGACG", "CAGCTTAC", "GGCAAGGA"]
SI_P01_C3 = ["ACGTTACA", "TTACCTAC", "GACGACGG", "CGTAGGTT"]
SI_P01_D3 = ["GAGCACGC", "CGAAGTTG", "TTCGTGAA", "ACTTCACT"]
SI_P01_E3 = ["TCTGCAGG", "CGGCTCCA", "AACAAGTC", "GTATGTAT"]
SI_P01_F3 = ["TTAGGACC", "AGTCTGTA", "GCCTCCGT", "CAGAATAG"]
SI_P01_G3 = ["TACGAGTT", "ATGTCCAG", "GCTATAGC", "CGACGTCA"]
SI_P01_H3 = ["TTGGGCTT", "GACAAACC", "ACACCTAA", "CGTTTGGG"]
SI_P01_A4 = ["CATGGCAG", "AGAACGCC", "GTCTTTGA", "TCGCAATT"]
SI_P01_B4 = ["GACAGGCT", "CCTCTAAC", "AGGGACTG", "TTATCTGA"]
SI_P01_C4 = ["ACATTGGC", "GAGCCCAT", "CTTAGTCA", "TGCGAATG"]
SI_P01_D4 = ["AAATCGTC", "GCGATCGG", "CTTCGAAT", "TGCGATCA"]
SI_P01_E4 = ["GTAAACAT", "TATCCTGA", "AGCTGACG", "CCGGTGTC"]
SI_P01_F4 = ["GCATGATA", "CGTCCTCT", "AACGACAC", "TTGATGGG"]
SI_P01_G4 = ["CCTGCGGT", "GTACAACG", "AGCTTCTC", "TAGAGTAA"]
SI_P01_H4 = ["TTCCATCT", "ACTGGAGC", "CGGTCGTG", "GAAATCAA"]
SI_P01_A5 = ["CAGTCTGG", "TCACACTC", "ATTGGGAA", "GGCATACT"]
SI_P01_B5 = ["TCATGCGA", "ATCGTACT", "CATCAGTG", "GGGACTAC"]
SI_P01_C5 = ["TCAGTCAA", "CACTGACT", "ATGCATTC", "GGTACGGG"]
SI_P01_D5 = ["GTCGACTC", "AGACGGAT", "CCTTTAGA", "TAGACTCG"]
SI_P01_E5 = ["CCGTTGAA", "TATGCTCT", "ATCCAAGG", "GGAAGCTC"]
SI_P01_F5 = ["TCTGACTA", "GTACGGCT", "CGGTTTAG", "AACACAGC"]
SI_P01_G5 = ["ATGAAGTA", "GAAGCTCG", "TCTTTCGT", "CGCCGAAC"]
SI_P01_H5 = ["ATAGTATG", "TATAAGGA", "GGCTCCAC", "CCGCGTCT"]
SI_P01_A6 = ["CTTTCGAC", "ACGGGACT", "TGCATCTG", "GAACATGA"]
SI_P01_B6 = ["GCGCACCT", "AACGCGAA", "CTATTTGG", "TGTAGATC"]
SI_P01_C6 = ["CGCTCAGG", "GAGGTTTA", "ACTCAGAC", "TTAAGCCT"]
SI_P01_D6 = ["GAAGTCTT", "TGCAGGGC", "ATGCCAAA", "CCTTATCG"]
SI_P01_E6 = ["TGATGGCT", "GCCATTTG", "ATTGAAAC", "CAGCCCGA"]
SI_P01_F6 = ["GACTTCCT", "TGAGGAAG", "ATGCCGGC", "CCTAATTA"]
SI_P01_G6 = ["GTGCGACA", "TCAGTGTT", "AGCACTGG", "CATTACAC"]
SI_P01_H6 = ["AAGCATAA", "CCCATCGC", "TTAGCGCT", "GGTTGATG"]
SI_P01_A7 = ["CTCATCAT", "TAACGTCC", "AGGTCATA", "GCTGAGGG"]
SI_P01_B7 = ["TCCACACG", "CTTCTGTT", "GAATGCAC", "AGGGATGA"]
SI_P01_C7 = ["GGCGGAAT", "ACACCGGG", "CATAATCC", "TTGTTCTA"]
SI_P01_D7 = ["CCGGATCC", "GGTCGCAT", "TTAACGTG", "AACTTAGA"]
SI_P01_E7 = ["AAGACGTG", "CCATGTGT", "GTTCACAA", "TGCGTACC"]
SI_P01_F7 = ["GGTTAGAC", "CAAACTTT", "ACCCGAGA", "TTGGTCCG"]
SI_P01_G7 = ["GCCGGTAA", "TGACTGCC", "ATTACCGG", "CAGTAATT"]
SI_P01_H7 = ["TGGCACGA", "AACGGGTG", "CTAATTCT", "GCTTCAAC"]
SI_P01_A8 = ["GACTGTTC", "ATGATACG", "CCACAGAA", "TGTGCCGT"]
SI_P01_B8 = ["ACGTTCAC", "TGCCCAGA", "CAAGGTCT", "GTTAAGTG"]
SI_P01_C8 = ["TTTATCCC", "GCACGTTT", "CAGGAAGA", "AGCTCGAG"]
SI_P01_D8 = ["AATCTTTG", "GGATGAGT", "CTCAAGAC", "TCGGCCCA"]
SI_P01_E8 = ["GCTTACAT", "TAGGGTGC", "AGCCTATG", "CTAACGCA"]
SI_P01_F8 = ["AGTTGGGA", "TACATTCT", "CCAGAAAG", "GTGCCCTC"]
SI_P01_G8 = ["AAGTACTC", "GGAACTCT", "TCCCTGAG", "CTTGGAGA"]
SI_P01_H8 = ["AAGAGCGG", "TCATAGCA", "GGCCCATC", "CTTGTTAT"]
SI_P01_A9 = ["GAGTGCGT", "CTCCAACA", "ACAACTTG", "TGTGTGAC"]
SI_P01_B9 = ["AAGCGTGT", "CTTGACCG", "TGATTAAC", "GCCACGTA"]
SI_P01_C9 = ["AGATCGGT", "CATCGTCG", "GTCATATA", "TCGGACAC"]
SI_P01_D9 = ["CAAGGGAC", "ACCTACTG", "GGGACACA", "TTTCTTGT"]
SI_P01_E9 = ["AGTAAGCA", "TACCGCGG", "CCGGTAAT", "GTATCTTC"]
SI_P01_F9 = ["AGTTAGTT", "GTACTTAA", "CACGCACG", "TCGAGCGC"]
SI_P01_G9 = ["TTGACTTC", "GCCGAAGT", "CAATGGCA", "AGTCTCAG"]
SI_P01_H9 = ["GGAATATG", "ACCTGCCA", "CTTCATAC", "TAGGCGGT"]
SI_P01_A10 = ["ACAGCAAC", "TTTCGCGA", "CGCAATTT", "GAGTTGCG"]
SI_P01_B10 = ["ACCATTAA", "CTGGACGT", "GAACGGTC", "TGTTCACG"]
SI_P01_C10 = ["CGTGCTAA", "TCACTCCT", "ATCTGATC", "GAGAAGGG"]
SI_P01_D10 = ["CTTATTTG", "GCGGGCAT", "AGATAACA", "TACCCGGC"]
SI_P01_E10 = ["GCACCAGT", "CGCAGGAG", "TAGTACCA", "ATTGTTTC"]
SI_P01_F10 = ["TCGACAAT", "GAATACTG", "ATTCGTGC", "CGCGTGCA"]
SI_P01_G10 = ["CGGAGACT", "TCCTATGA", "ATACTGAG", "GATGCCTC"]
SI_P01_H10 = ["GACCGCCA", "TCGAATTG", "ATTTCAGC", "CGAGTGAT"]
SI_P01_A11 = ["CTTTCCTT", "TAGGTAAA", "ACCAGTCC", "GGACAGGG"]
SI_P01_B11 = ["TCCAGATA", "GATTCGCT", "CGACATAG", "ATGGTCGC"]
SI_P01_C11 = ["GTTTGTGG", "ACCGAACA", "TAGACGAC", "CGACTCTT"]
SI_P01_D11 = ["GCTACTTC", "CACCTCAG", "ATATGAGA", "TGGGAGCT"]
SI_P01_E11 = ["ATCGCCAT", "TCACGGTA", "GGGTTTCC", "CATAAAGG"]
SI_P01_F11 = ["GAACCCGG", "AGCAGTTA", "TCGTAGAT", "CTTGTACC"]
SI_P01_G11 = ["AGGGCGTT", "CTATACGC", "TACATAAG", "GCTCGTCA"]
SI_P01_H11 = ["TCTCGACT", "AGGATCGA", "CACGATTC", "GTATCGAG"]
SI_P01_A12 = ["TTATGGAA", "ACTACTGT", "CGGGAACG", "GACCTCTC"]
SI_P01_B12 = ["GAAAGACA", "CGCTACAT", "ACGCTTGG", "TTTGCGTC"]
SI_P01_C12 = ["TAAGCCAC", "CCGTTATG", "GGTAATGT", "ATCCGGCA"]
SI_P01_D12 = ["GCTGTGTA", "AGAAACGT", "CACTCAAC", "TTGCGTCG"]
SI_P01_E12 = ["CGCTATCC", "ACGCGGAA", "TAAATCGT", "GTTGCATG"]
SI_P01_F12 = ["AATTGAAC", "TGGACCCT", "CCAGTGGA", "GTCCATTG"]
SI_P01_G12 = ["CATGCGTA", "ACCCGCAC", "TGATATCG", "GTGATAGT"]
SI_P01_H12 = ["TGTGTATA", "GTCCAGGC", "CAATCCCT", "ACGAGTAG"]

# WGS+ Tubes
SI_T2_1 = ["GGGTGATC", "TTACCGAT", "AATGACGA", "CCCATTCG"]
SI_T2_2 = ["GGGTCGAA", "ATCCGCCC", "TCTATAGT", "CAAGATTG"]
SI_T2_3 = ["GCTGATAT", "TGCCGAGC", "AAATTGCG", "CTGACCTA"]
SI_T2_4 = ["ACTTCTGA", "TTCATCTT", "CGACGACG", "GAGGAGAC"]
SI_T2_5 = ["GAATACAA", "AGCATACC", "TCGGGTTT", "CTTCCGGG"]
SI_T2_6 = ["TATTGAGA", "GTAGTCAG", "CGCCATTC", "ACGACGCT"]
SI_T2_7 = ["AAATCTGT", "GTCCAACC", "TCTGGCTG", "CGGATGAA"]
SI_T2_8 = ["CCTTGAAC", "GAAATCGG", "TGGCCTCT", "ATCGAGTA"]

SI_NA_A1 = SI_3A_A1 = SI_P03_A1 = ["AAACGGCG", "CCTACCAT", "GGCGTTTC", "TTGTAAGA"]
SI_NA_B1 = SI_3A_B1 = SI_P03_B1 = ["AGGCTACC", "CTAGCTGT", "GCCAACAA", "TATTGGTG"]
SI_NA_C1 = SI_3A_C1 = SI_P03_C1 = ["AGACTTTC", "CCGAGGCA", "GATGCAGT", "TTCTACAG"]
SI_NA_D1 = SI_3A_D1 = SI_P03_D1 = ["AGCTGCGT", "CAACCATC", "GTGGAGCA", "TCTATTAG"]
SI_NA_E1 = SI_3A_E1 = SI_P03_E1 = ["ACGAAAGC", "CGCCCGTA", "GTTTGCCT", "TAAGTTAG"]
SI_NA_F1 = SI_3A_F1 = SI_P03_F1 = ["ATCGCTCC", "CCGTACAG", "GATAGGTA", "TGACTAGT"]
SI_NA_G1 = SI_3A_G1 = SI_P03_G1 = ["ATGCGATT", "CATATGCG", "GGATACGA", "TCCGCTAC"]
SI_NA_H1 = SI_3A_H1 = SI_P03_H1 = ["AAACTCAT", "CGGGAGTA", "GTCACAGG", "TCTTGTCC"]
SI_NA_A2 = SI_3A_A2 = SI_P03_A2 = ["AGCCCTTT", "CAAGTCCA", "GTGAGAAG", "TCTTAGGC"]
SI_NA_B2 = SI_3A_B2 = SI_P03_B2 = ["AAGTTGAT", "CCCACCCA", "GGTCGAGC", "TTAGATTG"]
SI_NA_C2 = SI_3A_C2 = SI_P03_C2 = ["AATCACTA", "CCGAGAAC", "GTAGTGCG", "TGCTCTGT"]
SI_NA_D2 = SI_3A_D2 = SI_P03_D2 = ["ACATTCCG", "CTGCGGTA", "GACACAAT", "TGTGATGC"]
SI_NA_E2 = SI_3A_E2 = SI_P03_E2 = ["AGGCTGGT", "CACAACTA", "GTTGGTCC", "TCATCAAG"]
SI_NA_F2 = SI_3A_F2 = SI_P03_F2 = ["ATGGTTAG", "CATTGATA", "GCAAACGC", "TGCCCGCT"]
SI_NA_G2 = SI_3A_G2 = SI_P03_G2 = ["ATAACCTA", "CGGTGAGC", "GATCTTAT", "TCCGAGCG"]
SI_NA_H2 = SI_3A_H2 = SI_P03_H2 = ["AACGGTCA", "CCGAACTC", "GGTCCAAG", "TTATTGGT"]
SI_NA_A3 = SI_3A_A3 = SI_P03_A3 = ["AAAGCATA", "CTGCAGCC", "GCCTTTAT", "TGTAGCGG"]
SI_NA_B3 = SI_3A_B3 = SI_P03_B3 = ["ATTGGACG", "CAGCTTAC", "GGCAAGGA", "TCATCCTT"]
SI_NA_C3 = SI_3A_C3 = SI_P03_C3 = ["ACGTTACA", "CGTAGGTT", "GACGACGG", "TTACCTAC"]
SI_NA_D3 = SI_3A_D3 = SI_P03_D3 = ["ACTTCACT", "CGAAGTTG", "GAGCACGC", "TTCGTGAA"]
SI_NA_E3 = SI_3A_E3 = SI_P03_E3 = ["AACAAGTC", "CGGCTCCA", "GTATGTAT", "TCTGCAGG"]
SI_NA_F3 = SI_3A_F3 = SI_P03_F3 = ["AGTCTGTA", "CAGAATAG", "GCCTCCGT", "TTAGGACC"]
SI_NA_G3 = SI_3A_G3 = SI_P03_G3 = ["ATGTCCAG", "CGACGTCA", "GCTATAGC", "TACGAGTT"]
SI_NA_H3 = SI_3A_H3 = SI_P03_H3 = ["ACACCTAA", "CGTTTGGG", "GACAAACC", "TTGGGCTT"]
SI_NA_A4 = SI_3A_A4 = SI_P03_A4 = ["AGAACGCC", "CATGGCAG", "GTCTTTGA", "TCGCAATT"]
SI_NA_B4 = SI_3A_B4 = SI_P03_B4 = ["AGGGACTG", "CCTCTAAC", "GACAGGCT", "TTATCTGA"]
SI_NA_C4 = SI_3A_C4 = SI_P03_C4 = ["ACATTGGC", "CTTAGTCA", "GAGCCCAT", "TGCGAATG"]
SI_NA_D4 = SI_3A_D4 = SI_P03_D4 = ["AAATCGTC", "CTTCGAAT", "GCGATCGG", "TGCGATCA"]
SI_NA_E4 = SI_3A_E4 = SI_P03_E4 = ["AGCTGACG", "CCGGTGTC", "GTAAACAT", "TATCCTGA"]
SI_NA_F4 = SI_3A_F4 = SI_P03_F4 = ["AACGACAC", "CGTCCTCT", "GCATGATA", "TTGATGGG"]
SI_NA_G4 = SI_3A_G4 = SI_P03_G4 = ["AGCTTCTC", "CCTGCGGT", "GTACAACG", "TAGAGTAA"]
SI_NA_H4 = SI_3A_H4 = SI_P03_H4 = ["ACTGGAGC", "CGGTCGTG", "GAAATCAA", "TTCCATCT"]
SI_NA_A5 = SI_3A_A5 = SI_P03_A5 = ["ATTGGGAA", "CAGTCTGG", "GGCATACT", "TCACACTC"]
SI_NA_B5 = SI_3A_B5 = SI_P03_B5 = ["ATCGTACT", "CATCAGTG", "GGGACTAC", "TCATGCGA"]
SI_NA_C5 = SI_3A_C5 = SI_P03_C5 = ["ATGCATTC", "CACTGACT", "GGTACGGG", "TCAGTCAA"]
SI_NA_D5 = SI_3A_D5 = SI_P03_D5 = ["AGACGGAT", "CCTTTAGA", "GTCGACTC", "TAGACTCG"]
SI_NA_E5 = SI_3A_E5 = SI_P03_E5 = ["ATCCAAGG", "CCGTTGAA", "GGAAGCTC", "TATGCTCT"]
SI_NA_F5 = SI_3A_F5 = SI_P03_F5 = ["AACACAGC", "CGGTTTAG", "GTACGGCT", "TCTGACTA"]
SI_NA_G5 = SI_3A_G5 = SI_P03_G5 = ["ATGAAGTA", "CGCCGAAC", "GAAGCTCG", "TCTTTCGT"]
SI_NA_H5 = SI_3A_H5 = SI_P03_H5 = ["ATAGTATG", "CCGCGTCT", "GGCTCCAC", "TATAAGGA"]
SI_NA_A6 = SI_3A_A6 = SI_P03_A6 = ["ACGGGACT", "CTTTCGAC", "GAACATGA", "TGCATCTG"]
SI_NA_B6 = SI_3A_B6 = SI_P03_B6 = ["AACGCGAA", "CTATTTGG", "GCGCACCT", "TGTAGATC"]
SI_NA_C6 = SI_3A_C6 = SI_P03_C6 = ["ACTCAGAC", "CGCTCAGG", "GAGGTTTA", "TTAAGCCT"]
SI_NA_D6 = SI_3A_D6 = SI_P03_D6 = ["ATGCCAAA", "CCTTATCG", "GAAGTCTT", "TGCAGGGC"]
SI_NA_E6 = SI_3A_E6 = SI_P03_E6 = ["ATTGAAAC", "CAGCCCGA", "GCCATTTG", "TGATGGCT"]
SI_NA_F6 = SI_3A_F6 = SI_P03_F6 = ["ATGCCGGC", "CCTAATTA", "GACTTCCT", "TGAGGAAG"]
SI_NA_G6 = SI_3A_G6 = SI_P03_G6 = ["AGCACTGG", "CATTACAC", "GTGCGACA", "TCAGTGTT"]
SI_NA_H6 = SI_3A_H6 = SI_P03_H6 = ["AAGCATAA", "CCCATCGC", "GGTTGATG", "TTAGCGCT"]
SI_NA_A7 = SI_3A_A7 = SI_P03_A7 = ["AGGTCATA", "CTCATCAT", "GCTGAGGG", "TAACGTCC"]
SI_NA_B7 = SI_3A_B7 = SI_P03_B7 = ["AGGGATGA", "CTTCTGTT", "GAATGCAC", "TCCACACG"]
SI_NA_C7 = SI_3A_C7 = SI_P03_C7 = ["ACACCGGG", "CATAATCC", "GGCGGAAT", "TTGTTCTA"]
SI_NA_D7 = SI_3A_D7 = SI_P03_D7 = ["AACTTAGA", "CCGGATCC", "GGTCGCAT", "TTAACGTG"]
SI_NA_E7 = SI_3A_E7 = SI_P03_E7 = ["AAGACGTG", "CCATGTGT", "GTTCACAA", "TGCGTACC"]
SI_NA_F7 = SI_3A_F7 = SI_P03_F7 = ["ACCCGAGA", "CAAACTTT", "GGTTAGAC", "TTGGTCCG"]
SI_NA_G7 = SI_3A_G7 = SI_P03_G7 = ["ATTACCGG", "CAGTAATT", "GCCGGTAA", "TGACTGCC"]
SI_NA_H7 = SI_3A_H7 = SI_P03_H7 = ["AACGGGTG", "CTAATTCT", "GCTTCAAC", "TGGCACGA"]
SI_NA_A8 = SI_3A_A8 = SI_P03_A8 = ["ATGATACG", "CCACAGAA", "GACTGTTC", "TGTGCCGT"]
SI_NA_B8 = SI_3A_B8 = SI_P03_B8 = ["ACGTTCAC", "CAAGGTCT", "GTTAAGTG", "TGCCCAGA"]
SI_NA_C8 = SI_3A_C8 = SI_P03_C8 = ["AGCTCGAG", "CAGGAAGA", "GCACGTTT", "TTTATCCC"]
SI_NA_D8 = SI_3A_D8 = SI_P03_D8 = ["AATCTTTG", "CTCAAGAC", "GGATGAGT", "TCGGCCCA"]
SI_NA_E8 = SI_3A_E8 = SI_P03_E8 = ["AGCCTATG", "CTAACGCA", "GCTTACAT", "TAGGGTGC"]
SI_NA_F8 = SI_3A_F8 = SI_P03_F8 = ["AGTTGGGA", "CCAGAAAG", "GTGCCCTC", "TACATTCT"]
SI_NA_G8 = SI_3A_G8 = SI_P03_G8 = ["AAGTACTC", "CTTGGAGA", "GGAACTCT", "TCCCTGAG"]
SI_NA_H8 = SI_3A_H8 = SI_P03_H8 = ["AAGAGCGG", "CTTGTTAT", "GGCCCATC", "TCATAGCA"]
SI_NA_A9 = SI_3A_A9 = SI_P03_A9 = ["ACAACTTG", "CTCCAACA", "GAGTGCGT", "TGTGTGAC"]
SI_NA_B9 = SI_3A_B9 = SI_P03_B9 = ["AAGCGTGT", "CTTGACCG", "GCCACGTA", "TGATTAAC"]
SI_NA_C9 = SI_3A_C9 = SI_P03_C9 = ["AGATCGGT", "CATCGTCG", "GTCATATA", "TCGGACAC"]
SI_NA_D9 = SI_3A_D9 = SI_P03_D9 = ["ACCTACTG", "CAAGGGAC", "GGGACACA", "TTTCTTGT"]
SI_NA_E9 = SI_3A_E9 = SI_P03_E9 = ["AGTAAGCA", "CCGGTAAT", "GTATCTTC", "TACCGCGG"]
SI_NA_F9 = SI_3A_F9 = SI_P03_F9 = ["AGTTAGTT", "CACGCACG", "GTACTTAA", "TCGAGCGC"]
SI_NA_G9 = SI_3A_G9 = SI_P03_G9 = ["AGTCTCAG", "CAATGGCA", "GCCGAAGT", "TTGACTTC"]
SI_NA_H9 = SI_3A_H9 = SI_P03_H9 = ["ACCTGCCA", "CTTCATAC", "GGAATATG", "TAGGCGGT"]
SI_NA_A10 = SI_3A_A10 = SI_P03_A10 = ["ACAGCAAC", "CGCAATTT", "GAGTTGCG", "TTTCGCGA"]
SI_NA_B10 = SI_3A_B10 = SI_P03_B10 = ["ACCATTAA", "CTGGACGT", "GAACGGTC", "TGTTCACG"]
SI_NA_C10 = SI_3A_C10 = SI_P03_C10 = ["ATCTGATC", "CGTGCTAA", "GAGAAGGG", "TCACTCCT"]
SI_NA_D10 = SI_3A_D10 = SI_P03_D10 = ["AGATAACA", "CTTATTTG", "GCGGGCAT", "TACCCGGC"]
SI_NA_E10 = SI_3A_E10 = SI_P03_E10 = ["ATTGTTTC", "CGCAGGAG", "GCACCAGT", "TAGTACCA"]
SI_NA_F10 = SI_3A_F10 = SI_P03_F10 = ["ATTCGTGC", "CGCGTGCA", "GAATACTG", "TCGACAAT"]
SI_NA_G10 = SI_3A_G10 = SI_P03_G10 = ["ATACTGAG", "CGGAGACT", "GATGCCTC", "TCCTATGA"]
SI_NA_H10 = SI_3A_H10 = SI_P03_H10 = ["ATTTCAGC", "CGAGTGAT", "GACCGCCA", "TCGAATTG"]
SI_NA_A11 = SI_3A_A11 = SI_P03_A11 = ["ACCAGTCC", "CTTTCCTT", "GGACAGGG", "TAGGTAAA"]
SI_NA_B11 = SI_3A_B11 = SI_P03_B11 = ["ATGGTCGC", "CGACATAG", "GATTCGCT", "TCCAGATA"]
SI_NA_C11 = SI_3A_C11 = SI_P03_C11 = ["ACCGAACA", "CGACTCTT", "GTTTGTGG", "TAGACGAC"]
SI_NA_D11 = SI_3A_D11 = SI_P03_D11 = ["ATATGAGA", "CACCTCAG", "GCTACTTC", "TGGGAGCT"]
SI_NA_E11 = SI_3A_E11 = SI_P03_E11 = ["ATCGCCAT", "CATAAAGG", "GGGTTTCC", "TCACGGTA"]
SI_NA_F11 = SI_3A_F11 = SI_P03_F11 = ["AGCAGTTA", "CTTGTACC", "GAACCCGG", "TCGTAGAT"]
SI_NA_G11 = SI_3A_G11 = SI_P03_G11 = ["AGGGCGTT", "CTATACGC", "GCTCGTCA", "TACATAAG"]
SI_NA_H11 = SI_3A_H11 = SI_P03_H11 = ["AGGATCGA", "CACGATTC", "GTATCGAG", "TCTCGACT"]
SI_NA_A12 = SI_3A_A12 = SI_P03_A12 = ["ACTACTGT", "CGGGAACG", "GACCTCTC", "TTATGGAA"]
SI_NA_B12 = SI_3A_B12 = SI_P03_B12 = ["ACGCTTGG", "CGCTACAT", "GAAAGACA", "TTTGCGTC"]
SI_NA_C12 = SI_3A_C12 = SI_P03_C12 = ["ATCCGGCA", "CCGTTATG", "GGTAATGT", "TAAGCCAC"]
SI_NA_D12 = SI_3A_D12 = SI_P03_D12 = ["AGAAACGT", "CACTCAAC", "GCTGTGTA", "TTGCGTCG"]
SI_NA_E12 = SI_3A_E12 = SI_P03_E12 = ["ACGCGGAA", "CGCTATCC", "GTTGCATG", "TAAATCGT"]
SI_NA_F12 = SI_3A_F12 = SI_P03_F12 = ["AATTGAAC", "CCAGTGGA", "GTCCATTG", "TGGACCCT"]
SI_NA_G12 = SI_3A_G12 = SI_P03_G12 = ["ACCCGCAC", "CATGCGTA", "GTGATAGT", "TGATATCG"]
SI_NA_H12 = SI_3A_H12 = SI_P03_H12 = ["ACGAGTAG", "CAATCCCT", "GTCCAGGC", "TGTGTATA"]

# Chromium WGS Plate
SI_GA_A1 = SI_P2_A1 = ["GGTTTACT", "CTAAACGG", "TCGGCGTC", "AACCGTAA"]
SI_GA_A2 = SI_P2_A2 = ["TTTCATGA", "ACGTCCCT", "CGCATGTG", "GAAGGAAC"]
SI_GA_A3 = SI_P2_A3 = ["CAGTACTG", "AGTAGTCT", "GCAGTAGA", "TTCCCGAC"]
SI_GA_A4 = SI_P2_A4 = ["TATGATTC", "CCCACAGT", "ATGCTGAA", "GGATGCCG"]
SI_GA_A5 = SI_P2_A5 = ["CTAGGTGA", "TCGTTCAG", "AGCCAATT", "GATACGCC"]
SI_GA_A6 = SI_P2_A6 = ["CGCTATGT", "GCTGTCCA", "TTGAGATC", "AAACCGAG"]
SI_GA_A7 = SI_P2_A7 = ["ACAGAGGT", "TATAGTTG", "CGGTCCCA", "GTCCTAAC"]
SI_GA_A8 = SI_P2_A8 = ["GCATCTCC", "TGTAAGGT", "CTGCGATG", "AACGTCAA"]
SI_GA_A9 = SI_P2_A9 = ["TCTTAAAG", "CGAGGCTC", "GTCCTTCT", "AAGACGGA"]
SI_GA_A10 = SI_P2_A10 = ["GAAACCCT", "TTTCTGTC", "CCGTGTGA", "AGCGAAAG"]
SI_GA_A11 = SI_P2_A11 = ["GTCCGGTC", "AAGATCAT", "CCTGAAGG", "TGATCTCA"]
SI_GA_A12 = SI_P2_A12 = ["AGTGGAAC", "GTCTCCTT", "TCACATCA", "CAGATGGG"]
SI_GA_B1 = SI_P2_B1 = ["GTAATCTT", "TCCGGAAG", "AGTTCGGC", "CAGCATCA"]
SI_GA_B2 = SI_P2_B2 = ["TACTCTTC", "CCTGTGCG", "GGACACGT", "ATGAGAAA"]
SI_GA_B3 = SI_P2_B3 = ["GTGTATTA", "TGTGCGGG", "ACCATAAC", "CAACGCCT"]
SI_GA_B4 = SI_P2_B4 = ["ACTTCATA", "GAGATGAC", "TGCCGTGG", "CTAGACCT"]
SI_GA_B5 = SI_P2_B5 = ["AATAATGG", "CCAGGGCA", "TGCCTCAT", "GTGTCATC"]
SI_GA_B6 = SI_P2_B6 = ["CGTTAATC", "GCCACGCT", "TTACTCAG", "AAGGGTGA"]
SI_GA_B7 = SI_P2_B7 = ["AAACCTCA", "GCCTTGGT", "CTGGACTC", "TGTAGAAG"]
SI_GA_B8 = SI_P2_B8 = ["AAAGTGCT", "GCTACCTG", "TGCTGTAA", "CTGCAAGC"]
SI_GA_B9 = SI_P2_B9 = ["CTGTAACT", "TCTAGCGA", "AGAGTGTG", "GACCCTAC"]
SI_GA_B10 = SI_P2_B10 = ["ACCGTATG", "GATTAGAT", "CTGACTGA", "TGACGCCC"]
SI_GA_B11 = SI_P2_B11 = ["GTTCCTCA", "AGGTACGC", "TAAGTATG", "CCCAGGAT"]
SI_GA_B12 = SI_P2_B12 = ["TACCACCA", "CTAAGTTT", "GGGTCAAG", "ACTGTGGC"]
SI_GA_C1 = SI_P2_C1 = ["CCACTTAT", "AACTGGCG", "TTGGCATA", "GGTAACGC"]
SI_GA_C2 = SI_P2_C2 = ["CCTAGACC", "ATCTCTGT", "TAGCTCTA", "GGAGAGAG"]
SI_GA_C3 = SI_P2_C3 = ["TCAGCCGT", "CAGAGGCC", "GGTCAATA", "ATCTTTAG"]
SI_GA_C4 = SI_P2_C4 = ["ACAATTCA", "TGCGCAGC", "CATCACTT", "GTGTGGAG"]
SI_GA_C5 = SI_P2_C5 = ["CGACTTGA", "TACAGACT", "ATTGCGTG", "GCGTACAC"]
SI_GA_C6 = SI_P2_C6 = ["ATTACTTC", "TGCGAACT", "GCATTCGG", "CAGCGGAA"]
SI_GA_C7 = SI_P2_C7 = ["GTCTCTCG", "AATCTCTC", "CGGAGGGA", "TCAGAAAT"]
SI_GA_C8 = SI_P2_C8 = ["GTTGAGAA", "AGATCTGG", "TCGATACT", "CACCGCTC"]
SI_GA_C9 = SI_P2_C9 = ["GCGCAGAA", "ATCTTACC", "TATGGTGT", "CGAACCTG"]
SI_GA_C10 = SI_P2_C10 = ["TCTCAGTG", "GAGACTAT", "CGCTTAGC", "ATAGGCCA"]
SI_GA_C11 = SI_P2_C11 = ["GAGGATCT", "AGACCATA", "TCCTGCGC", "CTTATGAG"]
SI_GA_C12 = SI_P2_C12 = ["TCTCGTTT", "GGCTAGCG", "ATGACCGC", "CAAGTAAA"]
SI_GA_D1 = SI_P2_D1 = ["CACTCGGA", "GCTGAATT", "TGAAGTAC", "ATGCTCCG"]
SI_GA_D2 = SI_P2_D2 = ["TAACAAGG", "GGTTCCTC", "ATCATGCA", "CCGGGTAT"]
SI_GA_D3 = SI_P2_D3 = ["ACATTACT", "TTTGGGTA", "CAGCCCAC", "GGCAATGG"]
SI_GA_D4 = SI_P2_D4 = ["CCCTAACA", "ATTCCGAT", "TGGATTGC", "GAAGGCTG"]
SI_GA_D5 = SI_P2_D5 = ["CTCGTCAC", "GATCAGCA", "ACAACAGG", "TGGTGTTT"]
SI_GA_D6 = SI_P2_D6 = ["CATGCGAT", "TGATATTC", "GTGATCGA", "ACCCGACG"]
SI_GA_D7 = SI_P2_D7 = ["ATTTGCTA", "TAGACACC", "CCACAGGG", "GGCGTTAT"]
SI_GA_D8 = SI_P2_D8 = ["GCAACAAA", "TAGTTGTC", "CGCCATCG", "ATTGGCGT"]
SI_GA_D9 = SI_P2_D9 = ["AGGAGATG", "GATGTGGT", "CTACATCC", "TCCTCCAA"]
SI_GA_D10 = SI_P2_D10 = ["CAATACCC", "TGTCTATG", "ACCACGAA", "GTGGGTGT"]
SI_GA_D11 = SI_P2_D11 = ["CTTTGCGG", "TGCACAAA", "AAGCAGTC", "GCAGTTCT"]
SI_GA_D12 = SI_P2_D12 = ["GCACAATG", "CTTGGTAC", "TGCACCGT", "AAGTTGCA"]
SI_GA_E1 = SI_P2_E1 = ["TGGTAAAC", "GAAAGGGT", "ACTGCTCG", "CTCCTCTA"]
SI_GA_E2 = SI_P2_E2 = ["GTGGTACC", "TACTATAG", "ACAAGGTA", "CGTCCCGT"]
SI_GA_E3 = SI_P2_E3 = ["AGGTATTG", "CTCCTAGT", "TCAAGGCC", "GATGCCAA"]
SI_GA_E4 = SI_P2_E4 = ["TTCGCCCT", "GGATGGGC", "AATCAATG", "CCGATTAA"]
SI_GA_E5 = SI_P2_E5 = ["CATTAGCG", "TTCGCTGA", "ACAAGAAT", "GGGCTCTC"]
SI_GA_E6 = SI_P2_E6 = ["CTGCGGCT", "GACTCAAA", "AGAAACTC", "TCTGTTGG"]
SI_GA_E7 = SI_P2_E7 = ["CACGCCTT", "GTATATAG", "TCTCGGGC", "AGGATACA"]
SI_GA_E8 = SI_P2_E8 = ["ATAGTTAC", "TGCTGAGT", "CCTACGTA", "GAGCACCG"]
SI_GA_E9 = SI_P2_E9 = ["TTGTTTCC", "GGAGGAGG", "CCTAACAA", "AACCCGTT"]
SI_GA_E10 = SI_P2_E10 = ["AAATGTGC", "GGGCAAAT", "TCTATCCG", "CTCGCGTA"]
SI_GA_E11 = SI_P2_E11 = ["AAGCGCTG", "CGTTTGAT", "GTAGCACA", "TCCAATGC"]
SI_GA_E12 = SI_P2_E12 = ["ACCGGCTC", "GAGTTAGT", "CGTCCTAG", "TTAAAGCA"]
SI_GA_F1 = SI_P2_F1 = ["GTTGCAGC", "TGGAATTA", "CAATGGAG", "ACCCTCCT"]
SI_GA_F2 = SI_P2_F2 = ["TTTACATG", "CGCGATAC", "ACGCGGGT", "GAATTCCA"]
SI_GA_F3 = SI_P2_F3 = ["TTCAGGTG", "ACGGACAT", "GATCTTGA", "CGATCACC"]
SI_GA_F4 = SI_P2_F4 = ["CCCAATAG", "GTGTCGCT", "AGAGTCGC", "TATCGATA"]
SI_GA_F5 = SI_P2_F5 = ["GACTACGT", "CTAGCGAG", "TCTATATC", "AGGCGTCA"]
SI_GA_F6 = SI_P2_F6 = ["CGGAGCAC", "GACCTATT", "ACTTAGGA", "TTAGCTCG"]
SI_GA_F7 = SI_P2_F7 = ["CGTGCAGA", "AACAAGAT", "TCGCTTCG", "GTATGCTC"]
SI_GA_F8 = SI_P2_F8 = ["CATGAACA", "TCACTCGC", "AGCTGGAT", "GTGACTTG"]
SI_GA_F9 = SI_P2_F9 = ["CAAGCTCC", "GTTCACTG", "TCGTGAAA", "AGCATGGT"]
SI_GA_F10 = SI_P2_F10 = ["GCTTGGCT", "AAACAAAC", "CGGGCTTA", "TTCATCGG"]
SI_GA_F11 = SI_P2_F11 = ["GCGAGAGT", "TACGTTCA", "AGTCCCAC", "CTATAGTG"]
SI_GA_F12 = SI_P2_F12 = ["TGATGCAT", "GCTACTGA", "CACCTGCC", "ATGGAATG"]
SI_GA_G1 = SI_P2_G1 = ["ATGAATCT", "GATCTCAG", "CCAGGAGC", "TGCTCGTA"]
SI_GA_G2 = SI_P2_G2 = ["TGATTCTA", "ACTAGGAG", "CAGCCACT", "GTCGATGC"]
SI_GA_G3 = SI_P2_G3 = ["CCTCATTC", "AGCATCCG", "GTGGCAAT", "TAATGGGA"]
SI_GA_G4 = SI_P2_G4 = ["GCGATGTG", "AGATACAA", "TTTCCACT", "CACGGTGC"]
SI_GA_G5 = SI_P2_G5 = ["GAGCAAGA", "TCTGTGAT", "CGCAGTTC", "ATATCCCG"]
SI_GA_G6 = SI_P2_G6 = ["CTGACGCG", "GGTCGTAC", "TCCTTCTT", "AAAGAAGA"]
SI_GA_G7 = SI_P2_G7 = ["GGTATGCA", "CTCGAAAT", "ACACCTTC", "TAGTGCGG"]
SI_GA_G8 = SI_P2_G8 = ["TATGAGCT", "CCGATAGC", "ATACCCAA", "GGCTGTTG"]
SI_GA_G9 = SI_P2_G9 = ["TAGGACGT", "ATCCCACA", "GGAATGTC", "CCTTGTAG"]
SI_GA_G10 = SI_P2_G10 = ["TCGCCAGC", "AATGTTAG", "CGATAGCT", "GTCAGCTA"]
SI_GA_G11 = SI_P2_G11 = ["TTATCGTT", "AGCAGAGC", "CATCTCCA", "GCGGATAG"]
SI_GA_G12 = SI_P2_G12 = ["ATTCTAAG", "CCCGATTA", "TGGAGGCT", "GAATCCGC"]
SI_GA_H1 = SI_P2_H1 = ["GTATGTCA", "TGTCAGAC", "CACGTCGG", "ACGACATT"]
SI_GA_H2 = SI_P2_H2 = ["TAATGACC", "ATGCCTTA", "GCCGAGAT", "CGTATCGG"]
SI_GA_H3 = SI_P2_H3 = ["CCAAGATG", "AGGCCCGA", "TACGTGAC", "GTTTATCT"]
SI_GA_H4 = SI_P2_H4 = ["GCCATTCC", "CAAGAATT", "TTGCCGGA", "AGTTGCAG"]
SI_GA_H5 = SI_P2_H5 = ["CCACTACA", "GATTCTGG", "TGCGGCTT", "ATGAAGAC"]
SI_GA_H6 = SI_P2_H6 = ["TAGGATAA", "CCTTTGTC", "GTACGCGG", "AGCACACT"]
SI_GA_H7 = SI_P2_H7 = ["AGCTATCA", "CATATAAC", "TCAGGGTG", "GTGCCCGT"]
SI_GA_H8 = SI_P2_H8 = ["TTGTTGAT", "GCTCAACC", "CAAAGTGG", "AGCGCCTA"]
SI_GA_H9 = SI_P2_H9 = ["ACACTGTT", "CAGGATGG", "GGCTGAAC", "TTTACCCA"]
SI_GA_H10 = SI_P2_H10 = ["GTAATTGC", "AGTCGCTT", "CACGAGAA", "TCGTCACG"]
SI_GA_H11 = SI_P2_H11 = ["GGCGAGTA", "ACTTCTAT", "CAAATACG", "TTGCGCGC"]
SI_GA_H12 = SI_P2_H12 = ["GACAGCAT", "TTTGTACA", "AGGCCGTG", "CCATATGC"]

# Dual indexing plate: i7, then i5 (use the workflow A i5 sequence)

# TT plate
SI_TT_A1 = ["GTAACATGCG", "AGTGTTACCT"]
SI_TT_A2 = ["GTGGATCAAA", "GCCAACCCTG"]
SI_TT_A3 = ["CACTACGAAA", "TTAGACTGAT"]
SI_TT_A4 = ["CTCTAGCGAG", "TATCTTCATC"]
SI_TT_A5 = ["GTAGCCCTGT", "GAGCATCTAT"]
SI_TT_A6 = ["TAACGCGTGA", "CCCTAACTTC"]
SI_TT_A7 = ["TCCCAAGGGT", "TACTACCTTT"]
SI_TT_A8 = ["CGAAGTATAC", "GAACTTGGAG"]
SI_TT_A9 = ["AAGTGGAGAG", "TTCCTGTTAC"]
SI_TT_A10 = ["CGTGACATGC", "ATGGTCTAAA"]
SI_TT_A11 = ["CGGAACCCAA", "GATTCGAGGA"]
SI_TT_A12 = ["CACCGCACCA", "GACTGTCAAT"]
SI_TT_B1 = ["ACAGTAACTA", "ACAGTTCGTT"]
SI_TT_B2 = ["TCTACCATTT", "CGGGAGAGTC"]
SI_TT_B3 = ["CACGGTGAAT", "GTTCGTCACA"]
SI_TT_B4 = ["GTAGACGAAA", "CTAGTGTGGT"]
SI_TT_B5 = ["TCGGCTCTAC", "CCGATGGTCT"]
SI_TT_B6 = ["AATGCCATGA", "TACGTAATGC"]
SI_TT_B7 = ["GCCTTCGGTA", "CCAACGATTT"]
SI_TT_B8 = ["GCACTGAGAA", "TATGCGTGAA"]
SI_TT_B9 = ["TATTGAGGCA", "CAGGTAAGTG"]
SI_TT_B10 = ["GCCCGATGGA", "AATCGTCTAG"]
SI_TT_B11 = ["TCTTACTTGC", "TGACCTCTAG"]
SI_TT_B12 = ["CGTCAAGGGC", "TAGGTCACTC"]
SI_TT_C1 = ["TGCGCGGTTT", "CAAGGATAAA"]
SI_TT_C2 = ["CAATCCCGAC", "CCGAGTAGTA"]
SI_TT_C3 = ["ATGGCTTGTG", "GAATGTTGTG"]
SI_TT_C4 = ["TTCTCGATGA", "TGTCGGGCAC"]
SI_TT_C5 = ["TCCGTTGGAT", "ACGTTCTCGC"]
SI_TT_C6 = ["ACGACTACCA", "ACGACCCTAA"]
SI_TT_C7 = ["CGCGCACTTA", "CCTGTATTCT"]
SI_TT_C8 = ["GCTACAAAGC", "CACGTGCCCT"]
SI_TT_C9 = ["TATCAGCCTA", "GTTTCGTCCT"]
SI_TT_C10 = ["AGAATGGTTT", "GAGGGTGGGA"]
SI_TT_C11 = ["ATGGGTGAAA", "CTTGGGAATT"]
SI_TT_C12 = ["TCGTCAAGAT", "GCAACTCAGG"]
SI_TT_D1 = ["TGCAATGTTC", "GCTTGTCGAA"]
SI_TT_D2 = ["TTAATACGCG", "CACCTCGGGT"]
SI_TT_D3 = ["CCTTCTAGAG", "AATACAACGA"]
SI_TT_D4 = ["GCAGTATAGG", "TTCCGTGCAC"]
SI_TT_D5 = ["TGGTTCGGGT", "GTGGCAGGAG"]
SI_TT_D6 = ["CCCAGCTTCT", "GACACCAAAC"]
SI_TT_D7 = ["CCTGTCAGGG", "AGCCCGTAAC"]
SI_TT_D8 = ["CGCTGAAATC", "AGGTGTCTGC"]
SI_TT_D9 = ["TGGTCCCAAG", "CCTCTGGCGT"]
SI_TT_D10 = ["ATGCGAATGG", "ACAAGTGTCG"]
SI_TT_D11 = ["CGAATATTCG", "CTGGAAGCAA"]
SI_TT_D12 = ["GAATTGGTTA", "ACTCTAGTAG"]
SI_TT_E1 = ["TTATTCGAGG", "CTGTCCTGCT"]
SI_TT_E2 = ["ATGGAGGGAG", "ATAACCCATT"]
SI_TT_E3 = ["ACCAGACAAC", "AGGAACTAGG"]
SI_TT_E4 = ["AACCACGCAT", "ATTCAGGTTA"]
SI_TT_E5 = ["CGCGGTAGGT", "CAGGATGTTG"]
SI_TT_E6 = ["TTGAGAGTCA", "AACCTGGTAG"]
SI_TT_E7 = ["GTCCTTCGGC", "TCATGCACAG"]
SI_TT_E8 = ["GAGCAAGGGC", "ATTGACTTGG"]
SI_TT_E9 = ["TGTCCCAACG", "TCGATGTCCA"]
SI_TT_E10 = ["CACAATCCCA", "ATATCCACAA"]
SI_TT_E11 = ["TCCGGGACAA", "GTGAATGCCA"]
SI_TT_E12 = ["CGTCCACCTG", "CATTCATGAC"]
SI_TT_F1 = ["AAGATTGGAT", "AGCGGGATTT"]
SI_TT_F2 = ["AAGGGCCGCA", "CTGATTCCTC"]
SI_TT_F3 = ["GAGAGGATAT", "TTGAAATGGG"]
SI_TT_F4 = ["CCCACCACAA", "ACCTCCGCTT"]
SI_TT_F5 = ["CGGCTGGATG", "TGATAAGCAC"]
SI_TT_F6 = ["TTGCCCGTGC", "GCGTGAGATT"]
SI_TT_F7 = ["AATGTATCCA", "AATGAGCTTA"]
SI_TT_F8 = ["CTCCTTTAGA", "GACATAGCTC"]
SI_TT_F9 = ["GTCCCATCAA", "CGAACGTGAC"]
SI_TT_F10 = ["CCGGCAACTG", "CGGTTTAACA"]
SI_TT_F11 = ["TTCACACCTT", "TAGTGTACAC"]
SI_TT_F12 = ["GAGACGCACG", "CTATGAACAT"]
SI_TT_G1 = ["TGTAGTCATT", "CTTGATCGTA"]
SI_TT_G2 = ["CATGTGGGTT", "GATTCCTTTA"]
SI_TT_G3 = ["ATGACGTCGC", "AGGTCAGGAT"]
SI_TT_G4 = ["GCGCTTATGG", "GCCTGGCTAG"]
SI_TT_G5 = ["ATAGGGCGAG", "TGCATCGAGT"]
SI_TT_G6 = ["GCGGGTAAGT", "TAGCACTAAG"]
SI_TT_G7 = ["GTTTCACGAT", "TTCGGCCAAA"]
SI_TT_G8 = ["TAAGCAACTG", "CTATACTCAA"]
SI_TT_G9 = ["CCGGAGGAAG", "TGCGGATGTT"]
SI_TT_G10 = ["ACTTTACGTG", "TGAACGCCCT"]
SI_TT_G11 = ["GATAACCTGC", "CATTAGAAAC"]
SI_TT_G12 = ["CTTGCATAAA", "ATCAGGGCTT"]
SI_TT_H1 = ["ACAATGTGAA", "CGTACCGTTA"]
SI_TT_H2 = ["TAGCATAGTG", "CGGCTCTGTC"]
SI_TT_H3 = ["CCCGTTCTCG", "GACGGATTGG"]
SI_TT_H4 = ["AGTTTCCTGG", "TGCCACACAG"]
SI_TT_H5 = ["AGCAAGAAGC", "TTGTGTTTCT"]
SI_TT_H6 = ["CCTATCCTCG", "GAATACTAAC"]
SI_TT_H7 = ["ACCTCGAGCT", "TGTGTTCGAT"]
SI_TT_H8 = ["ATAAGGATAC", "ATAGATAGGG"]
SI_TT_H9 = ["AGAACTTAGA", "CGAGTCCTTT"]
SI_TT_H10 = ["TTATCTAGGG", "AAAGGCTCTA"]
SI_TT_H11 = ["ACAATCGATC", "TGACGGAATG"]
SI_TT_H12 = ["TGATGATTCA", "GTAGGAGTCG"]

# TN plate
SI_TN_A1 = ["AGTATCTGCA", "TCGCTAGCGA"]
SI_TN_A2 = ["TCTATGAGTG", "CAACCAACGA"]
SI_TN_A3 = ["TTATTGACAC", "GCGAACTGAT"]
SI_TN_A4 = ["GAACAACCTT", "GAACTGGTAC"]
SI_TN_A5 = ["TCTCGAATGT", "ACGATCGCGA"]
SI_TN_A6 = ["TTTGCTGGGT", "CAAATTCCGG"]
SI_TN_A7 = ["TCCGAATAAA", "ATGCTACCGC"]
SI_TN_A8 = ["GTTTGAAAGT", "GTACGCCATG"]
SI_TN_A9 = ["GCACGTGACA", "AGGAAGTCTG"]
SI_TN_A10 = ["GTCGTTGCCT", "AGAACTTCTT"]
SI_TN_A11 = ["TCGTACGATG", "ACCCTCCCAT"]
SI_TN_A12 = ["CGCGAGTAGG", "CCTGGTGACA"]
SI_TN_B1 = ["CATAGCATGA", "GACCTGCCTG"]
SI_TN_B2 = ["TACTGCAATA", "AGAGTCCATG"]
SI_TN_B3 = ["TGGCTACCGG", "CTGAGTCATT"]
SI_TN_B4 = ["ACGTTTGATT", "TACTGAGAGA"]
SI_TN_B5 = ["TGGGTGCACA", "CATGCATCAT"]
SI_TN_B6 = ["ACGAGCGGAA", "AACAACTAAG"]
SI_TN_B7 = ["CCATTGTAAG", "TACGAATTGA"]
SI_TN_B8 = ["TAGTAGTTTG", "TCATCGGGCG"]
SI_TN_B9 = ["GATGGAAGGT", "AAATTGAGCA"]
SI_TN_B10 = ["ACAGGTTACG", "AGATAAACAG"]
SI_TN_B11 = ["AGTAGTTTGG", "ATAGCATGCA"]
SI_TN_B12 = ["TCGCCATTTG", "ACGGGCATGT"]
SI_TN_C1 = ["AAGGGTTTAC", "TACTCACGCG"]
SI_TN_C2 = ["GCTTAAGCAA", "GCCTACCGAA"]
SI_TN_C3 = ["GTGATCTGGG", "ACTGTGTCGC"]
SI_TN_C4 = ["ATGCAAGATC", "ACGCCTCTGA"]
SI_TN_C5 = ["TCAAAGGGTT", "GATTACTGAG"]
SI_TN_C6 = ["TCAAGTAAAG", "CAGTGCTGTT"]
SI_TN_C7 = ["GCTGCTCCCA", "CTACAGGGTC"]
SI_TN_C8 = ["ATCTGTAGTT", "AGGCCCAATG"]
SI_TN_C9 = ["ATGGCGCAAA", "CGATGCAAGC"]
SI_TN_C10 = ["TAATGGGCAA", "GCGCATAGGC"]
SI_TN_C11 = ["TAACTGTAGT", "ATGACCGATA"]
SI_TN_C12 = ["AGCCTTCTCT", "CTGTCCGCGT"]
SI_TN_D1 = ["AGCGCCTTGC", "GTACGAAGTG"]
SI_TN_D2 = ["CAGTAATACA", "TTGAGCTGAG"]
SI_TN_D3 = ["ATAGAACCAC", "CTAACCTAAC"]
SI_TN_D4 = ["TTACAATCGT", "CAGATTGTAC"]
SI_TN_D5 = ["CTGCCTGGGT", "GACCAATAGC"]
SI_TN_D6 = ["GAAAGCGCGC", "GAAACATATC"]
SI_TN_D7 = ["TGTTCGCGAA", "TCGTGAAATA"]
SI_TN_D8 = ["GCGTAACGAT", "ATTCGTTCAA"]
SI_TN_D9 = ["TGTCAGTAAG", "AGATGACATC"]
SI_TN_D10 = ["CTACGTAGGT", "GTCCCACTTA"]
SI_TN_D11 = ["CCTAGGCAAA", "CAGAAATATC"]
SI_TN_D12 = ["TTAACGGACG", "CAAACGTCGC"]
SI_TN_E1 = ["GTCATCCTAT", "CTAGGGCAAA"]
SI_TN_E2 = ["CGACCCAGTG", "TCGCACCAAC"]
SI_TN_E3 = ["CATAGTTCGC", "TTTCGTAACT"]
SI_TN_E4 = ["TCACGTTGGG", "CTTTGCTCCA"]
SI_TN_E5 = ["TAATCTTCGG", "AGCCATCAAT"]
SI_TN_E6 = ["CCATCACCAC", "GTGATCCCAA"]
SI_TN_E7 = ["CCATTAGGCG", "GCATTTCATC"]
SI_TN_E8 = ["CTGGTGATAA", "AGGGACCTGG"]
SI_TN_E9 = ["CGTTGGTCCG", "GTAGCTGATA"]
SI_TN_E10 = ["CTTCCTACTT", "TCCTCCTGTA"]
SI_TN_E11 = ["AGACGCATCT", "TTGTACGTGG"]
SI_TN_E12 = ["TCGGGAGCTG", "CCAGACTGCA"]
SI_TN_F1 = ["CCTGGCTATA", "CCCTCACAAA"]
SI_TN_F2 = ["ACTTGTTCGA", "TGGATGGGTG"]
SI_TN_F3 = ["AACCATTAGT", "GTATGTCGGG"]
SI_TN_F4 = ["TTGCGGGACT", "TGAGGATCGC"]
SI_TN_F5 = ["GAGCGAAAGC", "TCCTTACCAA"]
SI_TN_F6 = ["AGCATCACAT", "TCGTAGAGGA"]
SI_TN_F7 = ["ACCATTGCAC", "ACAGTTAAGC"]
SI_TN_F8 = ["GTTCTGGAAC", "CGGGTACTGG"]
SI_TN_F9 = ["CGGACGACCT", "GTTGCGCCTC"]
SI_TN_F10 = ["TGGACCTTTG", "TAAATCTCTG"]
SI_TN_F11 = ["TCATATGTGA", "AAAGTGTTCT"]
SI_TN_F12 = ["CGCCCTCATC", "GCGTCTACGC"]
SI_TN_G1 = ["TCATCGTTCT", "AATTCGGGAA"]
SI_TN_G2 = ["GCACTACTGA", "CACTACGGTT"]
SI_TN_G3 = ["GTTATCACGA", "GCAACACCTC"]
SI_TN_G4 = ["CAGGCGAATA", "CCCTTTACCG"]
SI_TN_G5 = ["TAAGTAGAAG", "CGCGTTTCCT"]
SI_TN_G6 = ["CGAGGAGCAT", "CAGTAAGTCT"]
SI_TN_G7 = ["ATCACCGTTT", "TGTCGAGGAG"]
SI_TN_G8 = ["GACCGCCTTT", "TTTAACTCGT"]
SI_TN_G9 = ["TCCCGACCTG", "AACCCACCAA"]
SI_TN_G10 = ["ATTGTACAGT", "TTGGTTACGT"]
SI_TN_G11 = ["GACAATTGGG", "ACATTTGGAA"]
SI_TN_G12 = ["ATTGGCGCAA", "TCAATTGCAA"]
SI_TN_H1 = ["CGTTCCACAT", "GAGGGAGCCA"]
SI_TN_H2 = ["ATCTTGCAGC", "CGAGTAAGGA"]
SI_TN_H3 = ["CAGCTGTTAT", "AGTACGTGAG"]
SI_TN_H4 = ["CTACGACTGA", "CATCGCCCTC"]
SI_TN_H5 = ["GCTGGGATGC", "GACTAACTGG"]
SI_TN_H6 = ["CCGTCGCTGA", "AGGTGTTAGT"]
SI_TN_H7 = ["AAGTTAGTAC", "ACGCGGAATA"]
SI_TN_H8 = ["GACTCAGGGT", "GAGACCCTTC"]
SI_TN_H9 = ["TGCACAAGCG", "TGATGTTTGC"]
SI_TN_H10 = ["TTCGCTTAAC", "CCGCTCGTTA"]
SI_TN_H11 = ["AGACGACCGA", "CCACAGAACA"]
SI_TN_H12 = ["AGTGGAGGGA", "TGCATAGTTT"]

# TS plate
SI_TS_A1 = ["AATTTCGGGT", "CTCTCTCCTC"]
SI_TS_A2 = ["CTACTGAATT", "CGCTAGCGCT"]
SI_TS_A3 = ["CAAGCGTTAG", "CGCGAATGCG"]
SI_TS_A4 = ["GCTACCCGGT", "ATGTAATGGA"]
SI_TS_A5 = ["CTCAGCGGGA", "TTACGGATAA"]
SI_TS_A6 = ["TCAGAACTTT", "CGCAGTCCAC"]
SI_TS_A7 = ["TAAACCCTAG", "CTGATAGGAA"]
SI_TS_A8 = ["GTCTAGTTTG", "TGGTTGCAAC"]
SI_TS_A9 = ["CCACTTACGT", "TTGAAACACG"]
SI_TS_A10 = ["TACGGTTCAT", "CGTCCAAGAT"]
SI_TS_A11 = ["CTACCTTTCT", "TTCACAGGGA"]
SI_TS_A12 = ["GTACCGGTAT", "TTTGGATGGG"]
SI_TS_B1 = ["TATGACGAGT", "AGGATTCTCG"]
SI_TS_B2 = ["ACCTGGTACA", "TGGGTAAAGT"]
SI_TS_B3 = ["GTCACGGGTG", "TGTTATCGTT"]
SI_TS_B4 = ["ACCCGCTCGA", "GTCACCCGTA"]
SI_TS_B5 = ["GTGTCTAACT", "GCAAGCTCTC"]
SI_TS_B6 = ["CGGCCATAGG", "AGCTTCGTTC"]
SI_TS_B7 = ["CATGCTGCTC", "GTGGAAACCG"]
SI_TS_B8 = ["CGCATTTCTC", "CGCACAACCA"]
SI_TS_B9 = ["TCAGTGATGA", "CGACTCTCGC"]
SI_TS_B10 = ["CACCGTCGAT", "AGCTATTTCG"]
SI_TS_B11 = ["TCTAGACGAA", "TGAATTAGAG"]
SI_TS_B12 = ["CCAGGGTCAA", "CGACCTTGTC"]
SI_TS_C1 = ["TAGGGTCAAA", "TAGGCAATAA"]
SI_TS_C2 = ["TCCTTGGAGC", "CGTCAACCCA"]
SI_TS_C3 = ["ACCGACTGAT", "TCCTGGGTTC"]
SI_TS_C4 = ["GTTACTAGAT", "GACTGATCAT"]
SI_TS_C5 = ["CGAGTTGGGT", "ACTAGAAACA"]
SI_TS_C6 = ["CGCGCCAAAG", "AAATCCAAGG"]
SI_TS_C7 = ["GATCGCGGTA", "CGGAACCGTC"]
SI_TS_C8 = ["GCCACTTCGA", "GAATACGCCA"]
SI_TS_C9 = ["TGCTTAACGT", "TACACCCACA"]
SI_TS_C10 = ["CCATGGAGGC", "CGCCTAGGTT"]
SI_TS_C11 = ["CAGCCAGTAA", "GACATAATAC"]
SI_TS_C12 = ["TTTGAGATAC", "GCACTCCGTG"]
SI_TS_D1 = ["CTTCTAATGT", "AGTGCGCACT"]
SI_TS_D2 = ["AGGCTGATTC", "GCTAGATGAC"]
SI_TS_D3 = ["TTCTTTGTAG", "GTCCTCTAAG"]
SI_TS_D4 = ["AGACAAGTCA", "CCAGCAGCTT"]
SI_TS_D5 = ["ACACAGACAA", "AGACGCGCTA"]
SI_TS_D6 = ["ACTAAATGGG", "ACAAATCTGT"]
SI_TS_D7 = ["CTAGAAATTG", "CTTACTTTCG"]
SI_TS_D8 = ["GCGCAAACAA", "CTAGATAACT"]
SI_TS_D9 = ["GAGTAGGATT", "CGTATAGCAT"]
SI_TS_D10 = ["TTATGGTGCT", "TTATCCATGC"]
SI_TS_D11 = ["GAGTCCGCAA", "CTCTGGAACT"]
SI_TS_D12 = ["ACGGAATTAC", "GACAGGACGC"]
SI_TS_E1 = ["CACATAAACA", "TACTTCAAAC"]
SI_TS_E2 = ["ACCAATCGTG", "TCTCCACGGG"]
SI_TS_E3 = ["GTATAGGGTG", "AAACCCTCCA"]
SI_TS_E4 = ["CGCTTCCAGA", "TCCGGGTGCT"]
SI_TS_E5 = ["CGATGCCCAA", "AGTGGACTTA"]
SI_TS_E6 = ["CAGAGAGGGT", "CGATCGTTTA"]
SI_TS_E7 = ["TACCAGTGCG", "TACCAGGCTC"]
SI_TS_E8 = ["GTTAAACCGC", "AGCCGGCTTG"]
SI_TS_E9 = ["CTTAACGCTT", "GCTAGTGTGA"]
SI_TS_E10 = ["GAAATGACGG", "TGGAGAAGGG"]
SI_TS_E11 = ["TCTTCGAAGT", "ACCTGATATG"]
SI_TS_E12 = ["GCGCCACATG", "CATAGTTACA"]
SI_TS_F1 = ["GATAATACCG", "ACCACGTAAA"]
SI_TS_F2 = ["CTCAACCAGG", "GTCTGCAGAC"]
SI_TS_F3 = ["CTGGCCGAAG", "CATTATTCAC"]
SI_TS_F4 = ["TTTCGCAGGC", "CTCGATGCAC"]
SI_TS_F5 = ["ACTACGGACT", "GAAGCGCTTC"]
SI_TS_F6 = ["GCGAGTTTGG", "GCACCCGTAC"]
SI_TS_F7 = ["TTGAACCTCT", "GAAGATATAG"]
SI_TS_F8 = ["GTCGCGACAA", "CAATCTGCCA"]
SI_TS_F9 = ["TATGTTGTGC", "ATGGCTTAAT"]
SI_TS_F10 = ["TAAGATGCAC", "TCATAGCCAA"]
SI_TS_F11 = ["ATAGTCATAC", "GAAACTGGTC"]
SI_TS_F12 = ["GAATGGAAGG", "GTCGCTTGTA"]
SI_TS_G1 = ["TTGGCGGCAC", "GTAAGTTACT"]
SI_TS_G2 = ["TGATCAAAGG", "AACCTTACTA"]
SI_TS_G3 = ["CCAGACACGG", "AGAAAGCGGT"]
SI_TS_G4 = ["CATTTACCGT", "CACCTGTAAA"]
SI_TS_G5 = ["TGGCCGTGAC", "AACTGTAACG"]
SI_TS_G6 = ["CTGAAGTTGC", "GATCTTAAGC"]
SI_TS_G7 = ["TGAGTCAAGA", "GCAGATCCTA"]
SI_TS_G8 = ["CAGAGGTAAG", "TTTGCACTGA"]
SI_TS_G9 = ["TGAGTATCTG", "TGACTCGTTC"]
SI_TS_G10 = ["TACATATGCT", "GTAATCGTGA"]
SI_TS_G11 = ["AATAGCTATC", "AGTGTCGCTT"]
SI_TS_G12 = ["ACCCAGTTGT", "CTTCCCACAA"]
SI_TS_H1 = ["CAGGACTCTA", "CGTAGGATGG"]
SI_TS_H2 = ["GACCTCTATC", "CGAGGTGTAA"]
SI_TS_H3 = ["AAACAGGAGA", "TCGGCCCTTG"]
SI_TS_H4 = ["TCTATTGACA", "GTGAACAAAC"]
SI_TS_H5 = ["CCCGCTTGAA", "GCCCAAGGTA"]
SI_TS_H6 = ["AGTGACCAGT", "TTGTTAGACA"]
SI_TS_H7 = ["CGAGCGCAGT", "ACCTCAACTG"]
SI_TS_H8 = ["ATACCTAACT", "TATAATGGTG"]
SI_TS_H9 = ["CCTCCGTGTC", "GTTCCAGGTA"]
SI_TS_H10 = ["TGTGAATTTC", "GAACCACGTG"]
SI_TS_H11 = ["ACACCAGCCT", "GCTGGTTCGT"]
SI_TS_H12 = ["GACAGGCGGT", "CTGGACTTAG"]

# NT plate
SI_NT_A1 = ["ATTTACCGCA", "GACAATAAAG"]
SI_NT_A2 = ["TTGTCGTAGA", "CAATGTAGCA"]
SI_NT_A3 = ["AGTCCTGCGG", "TGACACAAGT"]
SI_NT_A4 = ["TTGTTCATGT", "TGACAGCTGA"]
SI_NT_A5 = ["TCAGGAAGGA", "GAACGTGCTT"]
SI_NT_A6 = ["CTGTTAGAGG", "CCACGCTTCG"]
SI_NT_A7 = ["AGATGAGAAT", "GTCGACGGGT"]
SI_NT_A8 = ["CCAAAGCCGG", "ACCGTGCACA"]
SI_NT_A9 = ["AGTCATAATG", "AGGCTTGAAA"]
SI_NT_A10 = ["TTCATCAGAG", "TTGTCGTCTC"]
SI_NT_A11 = ["GAAGCGCGAA", "CAGCGAAATT"]
SI_NT_A12 = ["ATCCGCCGAA", "GCTACAGAAT"]
SI_NT_B1 = ["CTTATTGTGG", "AGCTGTGGGT"]
SI_NT_B2 = ["ATTCGTTGGG", "CATCAGGAGC"]
SI_NT_B3 = ["GTGGCCTCAT", "TCGAAAGTGA"]
SI_NT_B4 = ["CTATGGCATC", "CTCTGAGCGC"]
SI_NT_B5 = ["AAACCACAGT", "CCGCAAATGG"]
SI_NT_B6 = ["ATGTATCCAC", "CAGGCTGAGG"]
SI_NT_B7 = ["GATGAGTCTG", "TATGTAACCG"]
SI_NT_B8 = ["CTCACAATAA", "CCGTGTTTAA"]
SI_NT_B9 = ["TCTGTCGCAA", "ATCCGAACTG"]
SI_NT_B10 = ["CATCGAGAAG", "GTGCATCCGC"]
SI_NT_B11 = ["ACGTATTGGG", "CAATCGCAAA"]
SI_NT_B12 = ["CTTACGCGAC", "CCTGTCGGAT"]
SI_NT_C1 = ["GATAGTGAAG", "CGTTCGCCAG"]
SI_NT_C2 = ["CTGTGCAATG", "ATGGTGCTTT"]
SI_NT_C3 = ["AAAGCTGAGC", "CAGGAACGAG"]
SI_NT_C4 = ["GTCCAAGTCG", "GTCATGGCAC"]
SI_NT_C5 = ["GATTTCCATC", "CTTATGGTCA"]
SI_NT_C6 = ["CTAAATGGAT", "AATCACATAC"]
SI_NT_C7 = ["ATTTCAGTTC", "GCAGCATTAA"]
SI_NT_C8 = ["TTGCGACGTC", "TTAATCCACA"]
SI_NT_C9 = ["GTACTGTCCA", "TTTGTTGGAA"]
SI_NT_C10 = ["AAACGGTTTA", "TCTTCGTTAC"]
SI_NT_C11 = ["CGATAGTTCT", "GCGATTTCCT"]
SI_NT_C12 = ["TACTTTAGCT", "GAGTTATTTG"]
SI_NT_D1 = ["CTGGGATTAA", "AGTAAAGTTC"]
SI_NT_D2 = ["TACACTATTC", "ATTGCAACGT"]
SI_NT_D3 = ["AGAGCTATTT", "CTGGCACCCA"]
SI_NT_D4 = ["AGGTCGTTAT", "AGGTTATCCA"]
SI_NT_D5 = ["GCTGGACAGG", "TAATCTCTGT"]
SI_NT_D6 = ["ACTTAGATGG", "AATGTTGAGT"]
SI_NT_D7 = ["AGGCGCGAGT", "TGTGTCTATA"]
SI_NT_D8 = ["GAGGTCGTAC", "CAACTGCGGG"]
SI_NT_D9 = ["CCCAATGAGC", "AGTTTCTGAT"]
SI_NT_D10 = ["ACATTCAGGG", "GTCCTGAGAG"]
SI_NT_D11 = ["AGAAACGGTG", "TCACCCAGCA"]
SI_NT_D12 = ["AGTTGCAAGT", "ATACTTCATG"]
SI_NT_E1 = ["GCCTAGAAAT", "ACTACTCCGG"]
SI_NT_E2 = ["TACAAAGATG", "CCGATGACGT"]
SI_NT_E3 = ["GCAGGCTTAG", "CGTCTATTGC"]
SI_NT_E4 = ["CAGCTCCAAT", "TAGGAGGGTG"]
SI_NT_E5 = ["TTTGGAGAAA", "CAGCCCTTGA"]
SI_NT_E6 = ["TGTCGCTTTC", "CCTAAAGGGT"]
SI_NT_E7 = ["GTGTTGCGAG", "CACTTTGAGC"]
SI_NT_E8 = ["GTCTGTTCTG", "TCTGATGCTT"]
SI_NT_E9 = ["TCGCTCAATC", "GCTTACGTGA"]
SI_NT_E10 = ["CGTTACTAGC", "AATGGCCATT"]
SI_NT_E11 = ["GTGCAGATTT", "TAAAGGCGAT"]
SI_NT_E12 = ["GTTACCGAAA", "CGTTTGAATC"]
SI_NT_F1 = ["CGGTATGGAA", "TGCAACTGGT"]
SI_NT_F2 = ["TCGGTTTAGT", "TAAAGTGTTC"]
SI_NT_F3 = ["CTTTGCTTTG", "ACATTCATTC"]
SI_NT_F4 = ["ATGATCGCAC", "GCGGTATGTA"]
SI_NT_F5 = ["CGGCGTGTTA", "TGAGACGCGG"]
SI_NT_F6 = ["TCATTTCCGC", "ACAGCTGTTG"]
SI_NT_F7 = ["TTGTGCCCAG", "TTGCGAGTTG"]
SI_NT_F8 = ["AGCCAACGTG", "TCAAAGGAAC"]
SI_NT_F9 = ["GATCCATACT", "ATCGAGAGAA"]
SI_NT_F10 = ["TTTCCATGAA", "CGGTTCTAAC"]
SI_NT_F11 = ["TCTTTATCGG", "CCCAATAGCG"]
SI_NT_F12 = ["GAACCCGATG", "TCTATCCGGG"]
SI_NT_G1 = ["GATGTCTGTG", "CGTGCTACCG"]
SI_NT_G2 = ["TGTTAGACTA", "TCATGACGAC"]
SI_NT_G3 = ["TAGAACGCTT", "GTCGCAAACG"]
SI_NT_G4 = ["AATTTGACGT", "AGAAGTGAGG"]
SI_NT_G5 = ["GAGTGGCCAC", "GATGCACAGT"]
SI_NT_G6 = ["ATCAGTTACG", "TACAATCTCT"]
SI_NT_G7 = ["TGTAAGCTTT", "CGGACTAGTC"]
SI_NT_G8 = ["GCTTCGGTCT", "CGCGGGTTAG"]
SI_NT_G9 = ["AGTCTAAGAC", "CTGAAGTGAA"]
SI_NT_G10 = ["TGAAACATTC", "CCTCCTGCCT"]
SI_NT_G11 = ["CCTCACGAAA", "TGCCCTGTGC"]
SI_NT_G12 = ["CTACGGGCTT", "AGGCGTCCCT"]
SI_NT_H1 = ["GCGGCGTAAA", "CACGCGATCA"]
SI_NT_H2 = ["TCTCCTTCGG", "TGTCCGTCGC"]
SI_NT_H3 = ["CCTTACCCAT", "TCCCGGCAAC"]
SI_NT_H4 = ["AAGGAACATC", "TATCTGTGGG"]
SI_NT_H5 = ["GTGGGAACTT", "GCACTTACAG"]
SI_NT_H6 = ["ACCGCACCAC", "TCGGATTATA"]
SI_NT_H7 = ["ACCTTTATCT", "CGAGTGCCAA"]
SI_NT_H8 = ["AGTAGCCCGT", "TTCGGGACCT"]
SI_NT_H9 = ["AGATAGCATA", "CATTTCCGGA"]
SI_NT_H10 = ["TGGCGTTAAA", "TGTTAAGATG"]
SI_NT_H11 = ["TCAGGCGAAA", "TCTCTGGAAG"]
SI_NT_H12 = ["AAGACATAGC", "ATGTGGACGT"]

SI_P2_A1_10bp = ["GGTTTACTAT", "CTAAACGGAT", "TCGGCGTCAT", "AACCGTAAAT"]
SI_P2_A2_10bp = ["TTTCATGAAT", "ACGTCCCTAT", "CGCATGTGAT", "GAAGGAACAT"]
SI_P2_A3_10bp = ["CAGTACTGAT", "AGTAGTCTAT", "GCAGTAGAAT", "TTCCCGACAT"]
SI_P2_A4_10bp = ["TATGATTCAT", "CCCACAGTAT", "ATGCTGAAAT", "GGATGCCGAT"]
SI_P2_A5_10bp = ["CTAGGTGAAT", "TCGTTCAGAT", "AGCCAATTAT", "GATACGCCAT"]
SI_P2_A6_10bp = ["CGCTATGTAT", "GCTGTCCAAT", "TTGAGATCAT", "AAACCGAGAT"]
SI_P2_A7_10bp = ["ACAGAGGTAT", "TATAGTTGAT", "CGGTCCCAAT", "GTCCTAACAT"]
SI_P2_A8_10bp = ["GCATCTCCAT", "TGTAAGGTAT", "CTGCGATGAT", "AACGTCAAAT"]
SI_P2_A9_10bp = ["TCTTAAAGAT", "CGAGGCTCAT", "GTCCTTCTAT", "AAGACGGAAT"]
SI_P2_A10_10bp = ["GAAACCCTAT", "TTTCTGTCAT", "CCGTGTGAAT", "AGCGAAAGAT"]
SI_P2_A11_10bp = ["GTCCGGTCAT", "AAGATCATAT", "CCTGAAGGAT", "TGATCTCAAT"]
SI_P2_A12_10bp = ["AGTGGAACAT", "GTCTCCTTAT", "TCACATCAAT", "CAGATGGGAT"]
SI_P2_B1_10bp = ["GTAATCTTAT", "TCCGGAAGAT", "AGTTCGGCAT", "CAGCATCAAT"]
SI_P2_B2_10bp = ["TACTCTTCAT", "CCTGTGCGAT", "GGACACGTAT", "ATGAGAAAAT"]
SI_P2_B3_10bp = ["GTGTATTAAT", "TGTGCGGGAT", "ACCATAACAT", "CAACGCCTAT"]
SI_P2_B4_10bp = ["ACTTCATAAT", "GAGATGACAT", "TGCCGTGGAT", "CTAGACCTAT"]
SI_P2_B5_10bp = ["AATAATGGAT", "CCAGGGCAAT", "TGCCTCATAT", "GTGTCATCAT"]
SI_P2_B6_10bp = ["CGTTAATCAT", "GCCACGCTAT", "TTACTCAGAT", "AAGGGTGAAT"]
SI_P2_B7_10bp = ["AAACCTCAAT", "GCCTTGGTAT", "CTGGACTCAT", "TGTAGAAGAT"]
SI_P2_B8_10bp = ["AAAGTGCTAT", "GCTACCTGAT", "TGCTGTAAAT", "CTGCAAGCAT"]
SI_P2_B9_10bp = ["CTGTAACTAT", "TCTAGCGAAT", "AGAGTGTGAT", "GACCCTACAT"]
SI_P2_B10_10bp = ["ACCGTATGAT", "GATTAGATAT", "CTGACTGAAT", "TGACGCCCAT"]
SI_P2_B11_10bp = ["GTTCCTCAAT", "AGGTACGCAT", "TAAGTATGAT", "CCCAGGATAT"]
SI_P2_B12_10bp = ["TACCACCAAT", "CTAAGTTTAT", "GGGTCAAGAT", "ACTGTGGCAT"]
SI_P2_C1_10bp = ["CCACTTATAT", "AACTGGCGAT", "TTGGCATAAT", "GGTAACGCAT"]
SI_P2_C2_10bp = ["CCTAGACCAT", "ATCTCTGTAT", "TAGCTCTAAT", "GGAGAGAGAT"]
SI_P2_C3_10bp = ["TCAGCCGTAT", "CAGAGGCCAT", "GGTCAATAAT", "ATCTTTAGAT"]
SI_P2_C4_10bp = ["ACAATTCAAT", "TGCGCAGCAT", "CATCACTTAT", "GTGTGGAGAT"]
SI_P2_C5_10bp = ["CGACTTGAAT", "TACAGACTAT", "ATTGCGTGAT", "GCGTACACAT"]
SI_P2_C6_10bp = ["ATTACTTCAT", "TGCGAACTAT", "GCATTCGGAT", "CAGCGGAAAT"]
SI_P2_C7_10bp = ["GTCTCTCGAT", "AATCTCTCAT", "CGGAGGGAAT", "TCAGAAATAT"]
SI_P2_C8_10bp = ["GTTGAGAAAT", "AGATCTGGAT", "TCGATACTAT", "CACCGCTCAT"]
SI_P2_C9_10bp = ["GCGCAGAAAT", "ATCTTACCAT", "TATGGTGTAT", "CGAACCTGAT"]
SI_P2_C10_10bp = ["TCTCAGTGAT", "GAGACTATAT", "CGCTTAGCAT", "ATAGGCCAAT"]
SI_P2_C11_10bp = ["GAGGATCTAT", "AGACCATAAT", "TCCTGCGCAT", "CTTATGAGAT"]
SI_P2_C12_10bp = ["TCTCGTTTAT", "GGCTAGCGAT", "ATGACCGCAT", "CAAGTAAAAT"]
SI_P2_D1_10bp = ["CACTCGGAAT", "GCTGAATTAT", "TGAAGTACAT", "ATGCTCCGAT"]
SI_P2_D2_10bp = ["TAACAAGGAT", "GGTTCCTCAT", "ATCATGCAAT", "CCGGGTATAT"]
SI_P2_D3_10bp = ["ACATTACTAT", "TTTGGGTAAT", "CAGCCCACAT", "GGCAATGGAT"]
SI_P2_D4_10bp = ["CCCTAACAAT", "ATTCCGATAT", "TGGATTGCAT", "GAAGGCTGAT"]
SI_P2_D5_10bp = ["CTCGTCACAT", "GATCAGCAAT", "ACAACAGGAT", "TGGTGTTTAT"]
SI_P2_D6_10bp = ["CATGCGATAT", "TGATATTCAT", "GTGATCGAAT", "ACCCGACGAT"]
SI_P2_D7_10bp = ["ATTTGCTAAT", "TAGACACCAT", "CCACAGGGAT", "GGCGTTATAT"]
SI_P2_D8_10bp = ["GCAACAAAAT", "TAGTTGTCAT", "CGCCATCGAT", "ATTGGCGTAT"]
SI_P2_D9_10bp = ["AGGAGATGAT", "GATGTGGTAT", "CTACATCCAT", "TCCTCCAAAT"]
SI_P2_D10_10bp = ["CAATACCCAT", "TGTCTATGAT", "ACCACGAAAT", "GTGGGTGTAT"]
SI_P2_D11_10bp = ["CTTTGCGGAT", "TGCACAAAAT", "AAGCAGTCAT", "GCAGTTCTAT"]
SI_P2_D12_10bp = ["GCACAATGAT", "CTTGGTACAT", "TGCACCGTAT", "AAGTTGCAAT"]
SI_P2_E1_10bp = ["TGGTAAACAT", "GAAAGGGTAT", "ACTGCTCGAT", "CTCCTCTAAT"]
SI_P2_E2_10bp = ["GTGGTACCAT", "TACTATAGAT", "ACAAGGTAAT", "CGTCCCGTAT"]
SI_P2_E3_10bp = ["AGGTATTGAT", "CTCCTAGTAT", "TCAAGGCCAT", "GATGCCAAAT"]
SI_P2_E4_10bp = ["TTCGCCCTAT", "GGATGGGCAT", "AATCAATGAT", "CCGATTAAAT"]
SI_P2_E5_10bp = ["CATTAGCGAT", "TTCGCTGAAT", "ACAAGAATAT", "GGGCTCTCAT"]
SI_P2_E6_10bp = ["CTGCGGCTAT", "GACTCAAAAT", "AGAAACTCAT", "TCTGTTGGAT"]
SI_P2_E7_10bp = ["CACGCCTTAT", "GTATATAGAT", "TCTCGGGCAT", "AGGATACAAT"]
SI_P2_E8_10bp = ["ATAGTTACAT", "TGCTGAGTAT", "CCTACGTAAT", "GAGCACCGAT"]
SI_P2_E9_10bp = ["TTGTTTCCAT", "GGAGGAGGAT", "CCTAACAAAT", "AACCCGTTAT"]
SI_P2_E10_10bp = ["AAATGTGCAT", "GGGCAAATAT", "TCTATCCGAT", "CTCGCGTAAT"]
SI_P2_E11_10bp = ["AAGCGCTGAT", "CGTTTGATAT", "GTAGCACAAT", "TCCAATGCAT"]
SI_P2_E12_10bp = ["ACCGGCTCAT", "GAGTTAGTAT", "CGTCCTAGAT", "TTAAAGCAAT"]
SI_P2_F1_10bp = ["GTTGCAGCAT", "TGGAATTAAT", "CAATGGAGAT", "ACCCTCCTAT"]
SI_P2_F2_10bp = ["TTTACATGAT", "CGCGATACAT", "ACGCGGGTAT", "GAATTCCAAT"]
SI_P2_F3_10bp = ["TTCAGGTGAT", "ACGGACATAT", "GATCTTGAAT", "CGATCACCAT"]
SI_P2_F4_10bp = ["CCCAATAGAT", "GTGTCGCTAT", "AGAGTCGCAT", "TATCGATAAT"]
SI_P2_F5_10bp = ["GACTACGTAT", "CTAGCGAGAT", "TCTATATCAT", "AGGCGTCAAT"]
SI_P2_F6_10bp = ["CGGAGCACAT", "GACCTATTAT", "ACTTAGGAAT", "TTAGCTCGAT"]
SI_P2_F7_10bp = ["CGTGCAGAAT", "AACAAGATAT", "TCGCTTCGAT", "GTATGCTCAT"]
SI_P2_F8_10bp = ["CATGAACAAT", "TCACTCGCAT", "AGCTGGATAT", "GTGACTTGAT"]
SI_P2_F9_10bp = ["CAAGCTCCAT", "GTTCACTGAT", "TCGTGAAAAT", "AGCATGGTAT"]
SI_P2_F10_10bp = ["GCTTGGCTAT", "AAACAAACAT", "CGGGCTTAAT", "TTCATCGGAT"]
SI_P2_F11_10bp = ["GCGAGAGTAT", "TACGTTCAAT", "AGTCCCACAT", "CTATAGTGAT"]
SI_P2_F12_10bp = ["TGATGCATAT", "GCTACTGAAT", "CACCTGCCAT", "ATGGAATGAT"]
SI_P2_G1_10bp = ["ATGAATCTAT", "GATCTCAGAT", "CCAGGAGCAT", "TGCTCGTAAT"]
SI_P2_G2_10bp = ["TGATTCTAAT", "ACTAGGAGAT", "CAGCCACTAT", "GTCGATGCAT"]
SI_P2_G3_10bp = ["CCTCATTCAT", "AGCATCCGAT", "GTGGCAATAT", "TAATGGGAAT"]
SI_P2_G4_10bp = ["GCGATGTGAT", "AGATACAAAT", "TTTCCACTAT", "CACGGTGCAT"]
SI_P2_G5_10bp = ["GAGCAAGAAT", "TCTGTGATAT", "CGCAGTTCAT", "ATATCCCGAT"]
SI_P2_G6_10bp = ["CTGACGCGAT", "GGTCGTACAT", "TCCTTCTTAT", "AAAGAAGAAT"]
SI_P2_G7_10bp = ["GGTATGCAAT", "CTCGAAATAT", "ACACCTTCAT", "TAGTGCGGAT"]
SI_P2_G8_10bp = ["TATGAGCTAT", "CCGATAGCAT", "ATACCCAAAT", "GGCTGTTGAT"]
SI_P2_G9_10bp = ["TAGGACGTAT", "ATCCCACAAT", "GGAATGTCAT", "CCTTGTAGAT"]
SI_P2_G10_10bp = ["TCGCCAGCAT", "AATGTTAGAT", "CGATAGCTAT", "GTCAGCTAAT"]
SI_P2_G11_10bp = ["TTATCGTTAT", "AGCAGAGCAT", "CATCTCCAAT", "GCGGATAGAT"]
SI_P2_G12_10bp = ["ATTCTAAGAT", "CCCGATTAAT", "TGGAGGCTAT", "GAATCCGCAT"]
SI_P2_H1_10bp = ["GTATGTCAAT", "TGTCAGACAT", "CACGTCGGAT", "ACGACATTAT"]
SI_P2_H2_10bp = ["TAATGACCAT", "ATGCCTTAAT", "GCCGAGATAT", "CGTATCGGAT"]
SI_P2_H3_10bp = ["CCAAGATGAT", "AGGCCCGAAT", "TACGTGACAT", "GTTTATCTAT"]
SI_P2_H4_10bp = ["GCCATTCCAT", "CAAGAATTAT", "TTGCCGGAAT", "AGTTGCAGAT"]
SI_P2_H5_10bp = ["CCACTACAAT", "GATTCTGGAT", "TGCGGCTTAT", "ATGAAGACAT"]
SI_P2_H6_10bp = ["TAGGATAAAT", "CCTTTGTCAT", "GTACGCGGAT", "AGCACACTAT"]
SI_P2_H7_10bp = ["AGCTATCAAT", "CATATAACAT", "TCAGGGTGAT", "GTGCCCGTAT"]
SI_P2_H8_10bp = ["TTGTTGATAT", "GCTCAACCAT", "CAAAGTGGAT", "AGCGCCTAAT"]
SI_P2_H9_10bp = ["ACACTGTTAT", "CAGGATGGAT", "GGCTGAACAT", "TTTACCCAAT"]
SI_P2_H10_10bp = ["GTAATTGCAT", "AGTCGCTTAT", "CACGAGAAAT", "TCGTCACGAT"]
SI_P2_H11_10bp = ["GGCGAGTAAT", "ACTTCTATAT", "CAAATACGAT", "TTGCGCGCAT"]
SI_P2_H12_10bp = ["GACAGCATAT", "TTTGTACAAT", "AGGCCGTGAT", "CCATATGCAT"]

# NN Plate
SI_NN_A1 = ["GCCTTGTCAA", "GATCCAATCA"]
SI_NN_A2 = ["AACTTCTTTG", "ATAAGCGGTA"]
SI_NN_A3 = ["TGGTTATAGA", "GAGCTCATAA"]
SI_NN_A4 = ["GTAGTGCATC", "ATTTGACGGT"]
SI_NN_A5 = ["GCTTGATTTA", "CGGGTGTGAC"]
SI_NN_A6 = ["GAAGTTTCGC", "TTTCAAAGCA"]
SI_NN_A7 = ["GCAGTTGTTT", "ACACTACTTT"]
SI_NN_A8 = ["GCCGCAAGTA", "AAAGGTCCGC"]
SI_NN_A9 = ["AAGTTGTATG", "TGTACAATGC"]
SI_NN_A10 = ["AGCAACCTTT", "TTCAGCGCTA"]
SI_NN_A11 = ["GACGAGGGTT", "TTACTTTGAC"]
SI_NN_A12 = ["TGAACAGTCG", "ATTTCTCAGA"]
SI_NN_B1 = ["CGAAAGGAGT", "ACACCAAACA"]
SI_NN_B2 = ["GAATGACTTG", "TGAGCTCGCT"]
SI_NN_B3 = ["GCCAGGGATT", "CAAGTTTAGG"]
SI_NN_B4 = ["CTTTGTCCGC", "GCTGTCCCGT"]
SI_NN_B5 = ["AGCTTGGGTG", "AGCGTATAGT"]
SI_NN_B6 = ["TCGCACCGGT", "TAGCCTCAGG"]
SI_NN_B7 = ["TTTAGGTAGG", "ACTGAGGGAC"]
SI_NN_B8 = ["GTTCGAGCGG", "CTGTGGGTTT"]
SI_NN_B9 = ["AGGGTATGGC", "GAGTCCGACT"]
SI_NN_B10 = ["TACCCACTAT", "TGGAACATAT"]
SI_NN_B11 = ["TTCAGGCTAC", "CTGGGTATTG"]
SI_NN_B12 = ["AGGAATAGAT", "TGCGGTCACG"]
SI_NN_C1 = ["ACAGCGCTGT", "GAGGGTCATC"]
SI_NN_C2 = ["GACGTACGGA", "ACCTCGCTTT"]
SI_NN_C3 = ["CTTAGATGCA", "CTATTCGACT"]
SI_NN_C4 = ["ACTCCTCAAC", "ATTCACGGGA"]
SI_NN_C5 = ["TCCATACTGT", "GAGCGACTTC"]
SI_NN_C6 = ["GCCAGAATGG", "GAATTGTATC"]
SI_NN_C7 = ["ATTGCAAGAC", "CGGTGACCAT"]
SI_NN_C8 = ["CAACATATCG", "AACTAAAGGC"]
SI_NN_C9 = ["CAGGGACCTC", "AATAGCAGCA"]
SI_NN_C10 = ["ATTTGGGAAT", "TCAGCCGAGT"]
SI_NN_C11 = ["TGGATAATTG", "TTTGTGATCA"]
SI_NN_C12 = ["CAGATTATGA", "GTGCCTGTAC"]
SI_NN_D1 = ["AATGGTAAGC", "CTGTGAAGTT"]
SI_NN_D2 = ["CATCCCTCGG", "AGGGTAGGCG"]
SI_NN_D3 = ["CTGGTCCGTC", "ACGAATAAGG"]
SI_NN_D4 = ["GTCGTAAATT", "GTAGTAGGCT"]
SI_NN_D5 = ["CAACACTGAT", "CAAACCAGGG"]
SI_NN_D6 = ["CAGACTGAAT", "TGCCTAACCG"]
SI_NN_D7 = ["CGGACACGCT", "TCACGATATA"]
SI_NN_D8 = ["CTCGGCTCTC", "TATACTTCCA"]
SI_NN_D9 = ["AAGCCTATCA", "GTAGTGAACA"]
SI_NN_D10 = ["ACTGTGCCAA", "TAACCGTTAT"]
SI_NN_D11 = ["CTACTCCCAT", "TACGTTGCGG"]
SI_NN_D12 = ["AGACTCTAAC", "GTGTCGATGT"]
SI_NN_E1 = ["TGAGCCGGCA", "TGCTGCATGT"]
SI_NN_E2 = ["TAGCTTGCGT", "GCTGCTAAAG"]
SI_NN_E3 = ["GTACACCGGG", "AACAGTCGCG"]
SI_NN_E4 = ["CGCGTAGACG", "AAAGTAGCTG"]
SI_NN_E5 = ["CCGATATATT", "AACTATCCGA"]
SI_NN_E6 = ["TTGGGCGGGA", "ATGTATCTGT"]
SI_NN_E7 = ["GTTTATGAGG", "GCCAAACAGC"]
SI_NN_E8 = ["TTGGATACTC", "CGTACTGAAG"]
SI_NN_E9 = ["GCTATCTATC", "AAAGATGGAT"]
SI_NN_E10 = ["ATGTGATCGC", "TGACCTACCT"]
SI_NN_E11 = ["TCCTCACATG", "AACAGATTCA"]
SI_NN_E12 = ["GCCTCCTAAT", "CTCCTCCTGT"]
SI_NN_F1 = ["CGAGGCTGAT", "TCGACTTTCT"]
SI_NN_F2 = ["CTCATGACAT", "TGTTCCGCAC"]
SI_NN_F3 = ["AACGCGGCAA", "GCCCGTTTAC"]
SI_NN_F4 = ["AACACCTCTC", "GATTGTATGA"]
SI_NN_F5 = ["AAATAACGCG", "ATAGAGGAGC"]
SI_NN_F6 = ["GAAATCTTGT", "TAGACGCCAC"]
SI_NN_F7 = ["TAGATGGACT", "CCAGGGATAT"]
SI_NN_F8 = ["CAATCTGTAT", "TCCCATCGTT"]
SI_NN_F9 = ["GCGAAAGTAT", "GTGTCACAGA"]
SI_NN_F10 = ["CCCAGAGCTT", "ATGCTGTAAT"]
SI_NN_F11 = ["GACTACAGGA", "AGTGACAAAG"]
SI_NN_F12 = ["CAATTCATGG", "ACGTAGTTCG"]
SI_NN_G1 = ["TGGGAAGGGC", "ACTAACGATG"]
SI_NN_G2 = ["TACTTCGCAT", "AACGGTGTCG"]
SI_NN_G3 = ["TAAACTGGCA", "CCGACCTCTT"]
SI_NN_G4 = ["TTGAAGAACT", "CAACACCAGG"]
SI_NN_G5 = ["TCCCTCGTCA", "ATCAGGTGTG"]
SI_NN_G6 = ["ACTGGCCTAA", "CGCTCCCTTG"]
SI_NN_G7 = ["TCATAATGCA", "GATGAGGCGA"]
SI_NN_G8 = ["CGCCACGTTA", "CTTTCATAGG"]
SI_NN_G9 = ["TGGACTAAGC", "CTTAACATCG"]
SI_NN_G10 = ["AAGCCCGGCA", "GAGTTTCCGT"]
SI_NN_G11 = ["ATAGTGGCGG", "TACTGTTGTT"]
SI_NN_G12 = ["CCAACCGGAC", "GTTCTATCTA"]
SI_NN_H1 = ["TTACAGAGGG", "GTTTATGGCA"]
SI_NN_H2 = ["TCCAACAACG", "GTCCGGGTTT"]
SI_NN_H3 = ["AAAGCATGTC", "AGATACTACT"]
SI_NN_H4 = ["AGAAGTCGTT", "AGGACATTTA"]
SI_NN_H5 = ["GCTAGCGTTC", "TCGCGTGGTG"]
SI_NN_H6 = ["CAACTAGCTT", "TCAACTAATC"]
SI_NN_H7 = ["AGGGCCAGTT", "TAGGGCAAAT"]
SI_NN_H8 = ["CTCTATGCGT", "CCTCTGATGC"]
SI_NN_H9 = ["GTCCATACAA", "AGCCACTCAC"]
SI_NN_H10 = ["AGGGATGCAA", "CTCATATCCT"]
SI_NN_H11 = ["TTCAAGTCCT", "CAGCAGCTAA"]
SI_NN_H12 = ["CTCCAACCTA", "GCACCGCATC"]

# NEB #E7874 plates
# Only A1 - H6 are used
# Taken from:
# https://www.neb.com/en/-/media/nebus/files/manuals/manuale7395_e7874_e7876_e7878.pdf
SI_NEB7874_A1 = ["CACTGTAG", "AAGCGACT"]
SI_NEB7874_B1 = ["GTGCACGA", "TGATAGGC"]
SI_NEB7874_C1 = ["ATGTTCCT", "TCAGCGCC"]
SI_NEB7874_D1 = ["CATTATGG", "AGTCACAT"]
SI_NEB7874_E1 = ["TCTTGTTT", "CCTTTCAC"]
SI_NEB7874_F1 = ["GGCTTACT", "CTTTCCCT"]
SI_NEB7874_G1 = ["ACGATATG", "GACAATTC"]
SI_NEB7874_H1 = ["ATCCGCAG", "ACACGACT"]
SI_NEB7874_A2 = ["AAGCGACT", "ACGAATCC"]
SI_NEB7874_B2 = ["TGATAGGC", "GTCTGAGT"]
SI_NEB7874_C2 = ["AACACCAC", "GGTGTGAG"]
SI_NEB7874_D2 = ["ACCTCTTC", "CTTGCATA"]
SI_NEB7874_E2 = ["GTCCGATC", "GCCAATCC"]
SI_NEB7874_F2 = ["GAGGACCA", "ATGCCGGT"]
SI_NEB7874_G2 = ["CGCTCTTA", "CATACCGT"]
SI_NEB7874_H2 = ["CTGAGCTC", "ATCAGAGC"]
SI_NEB7874_A3 = ["ACGAATCC", "ATTACCCA"]
SI_NEB7874_B3 = ["GTCTGAGT", "GACTTGTG"]
SI_NEB7874_C3 = ["CCTAAACT", "ACGAGGAG"]
SI_NEB7874_D3 = ["TGTCACAC", "TAATCTCG"]
SI_NEB7874_E3 = ["GATATGAA", "TACGGCAG"]
SI_NEB7874_F3 = ["AAGTGTGG", "TGCCCATC"]
SI_NEB7874_G3 = ["GTTGGCGT", "CAGCAGTC"]
SI_NEB7874_H3 = ["TAGCTGGC", "TACCGGCT"]
SI_NEB7874_A4 = ["ATTACCCA", "CACTGTAG"]
SI_NEB7874_B4 = ["GACTTGTG", "GTGCACGA"]
SI_NEB7874_C4 = ["CAGGTAAG", "CTCGAAAT"]
SI_NEB7874_D4 = ["AAGGAGAC", "CTCACAAC"]
SI_NEB7874_E4 = ["AGTCAGGT", "GTAACCAC"]
SI_NEB7874_F4 = ["ACCGTAAG", "CATATCCA"]
SI_NEB7874_G4 = ["TATGACGT", "CGCTAATC"]
SI_NEB7874_H4 = ["TTGGGTAC", "CTTCCAAC"]
SI_NEB7874_A5 = ["TTCAATAG", "TCCCACGA"]
SI_NEB7874_B5 = ["GTTTGCTC", "ACCAACAG"]
SI_NEB7874_C5 = ["AGAAGCCT", "GTCAGTAT"]
SI_NEB7874_D5 = ["CTAGGTTG", "ATTCGAGC"]
SI_NEB7874_E5 = ["TGTGTCAG", "CACCTGTA"]
SI_NEB7874_F5 = ["AGAACCAG", "CCGACTCT"]
SI_NEB7874_G5 = ["ATTGGACA", "TTGCTGGA"]
SI_NEB7874_H5 = ["ACCCGTTG", "CAGCTTCG"]
SI_NEB7874_A6 = ["ACCGGAGT", "AAGGAAGG"]
SI_NEB7874_B6 = ["CTTGACGA", "GCACACAA"]
SI_NEB7874_C6 = ["GCCACGAC", "CCTCGGGT"]
SI_NEB7874_D6 = ["TCTGGAAC", "TAGCACCT"]
SI_NEB7874_E6 = ["CACTAGAC", "TGAGGACT"]
SI_NEB7874_F6 = ["TTGCGTTA", "TTCCCGAA"]
SI_NEB7874_G6 = ["CCTATGCA", "GAGTCGAT"]
SI_NEB7874_H6 = ["CAACCGAG", "TACCTGTG"]

SAMPLE_INDEX_MAP = {
    # GemCode Tube labels
    "SI-001": SI_001,
    "SI-002": SI_002,
    "SI-003": SI_003,
    "SI-004": SI_004,
    "SI-005": SI_005,
    "SI-006": SI_006,
    "SI-007": SI_007,
    "SI-008": SI_008,
    # GemCode Plate labels
    "SI-P01-A1": SI_P01_A1,
    "SI-P01-B1": SI_P01_B1,
    "SI-P01-C1": SI_P01_C1,
    "SI-P01-D1": SI_P01_D1,
    "SI-P01-E1": SI_P01_E1,
    "SI-P01-F1": SI_P01_F1,
    "SI-P01-G1": SI_P01_G1,
    "SI-P01-H1": SI_P01_H1,
    "SI-P01-A2": SI_P01_A2,
    "SI-P01-B2": SI_P01_B2,
    "SI-P01-C2": SI_P01_C2,
    "SI-P01-D2": SI_P01_D2,
    "SI-P01-E2": SI_P01_E2,
    "SI-P01-F2": SI_P01_F2,
    "SI-P01-G2": SI_P01_G2,
    "SI-P01-H2": SI_P01_H2,
    "SI-P01-A3": SI_P01_A3,
    "SI-P01-B3": SI_P01_B3,
    "SI-P01-C3": SI_P01_C3,
    "SI-P01-D3": SI_P01_D3,
    "SI-P01-E3": SI_P01_E3,
    "SI-P01-F3": SI_P01_F3,
    "SI-P01-G3": SI_P01_G3,
    "SI-P01-H3": SI_P01_H3,
    "SI-P01-A4": SI_P01_A4,
    "SI-P01-B4": SI_P01_B4,
    "SI-P01-C4": SI_P01_C4,
    "SI-P01-D4": SI_P01_D4,
    "SI-P01-E4": SI_P01_E4,
    "SI-P01-F4": SI_P01_F4,
    "SI-P01-G4": SI_P01_G4,
    "SI-P01-H4": SI_P01_H4,
    "SI-P01-A5": SI_P01_A5,
    "SI-P01-B5": SI_P01_B5,
    "SI-P01-C5": SI_P01_C5,
    "SI-P01-D5": SI_P01_D5,
    "SI-P01-E5": SI_P01_E5,
    "SI-P01-F5": SI_P01_F5,
    "SI-P01-G5": SI_P01_G5,
    "SI-P01-H5": SI_P01_H5,
    "SI-P01-A6": SI_P01_A6,
    "SI-P01-B6": SI_P01_B6,
    "SI-P01-C6": SI_P01_C6,
    "SI-P01-D6": SI_P01_D6,
    "SI-P01-E6": SI_P01_E6,
    "SI-P01-F6": SI_P01_F6,
    "SI-P01-G6": SI_P01_G6,
    "SI-P01-H6": SI_P01_H6,
    "SI-P01-A7": SI_P01_A7,
    "SI-P01-B7": SI_P01_B7,
    "SI-P01-C7": SI_P01_C7,
    "SI-P01-D7": SI_P01_D7,
    "SI-P01-E7": SI_P01_E7,
    "SI-P01-F7": SI_P01_F7,
    "SI-P01-G7": SI_P01_G7,
    "SI-P01-H7": SI_P01_H7,
    "SI-P01-A8": SI_P01_A8,
    "SI-P01-B8": SI_P01_B8,
    "SI-P01-C8": SI_P01_C8,
    "SI-P01-D8": SI_P01_D8,
    "SI-P01-E8": SI_P01_E8,
    "SI-P01-F8": SI_P01_F8,
    "SI-P01-G8": SI_P01_G8,
    "SI-P01-H8": SI_P01_H8,
    "SI-P01-A9": SI_P01_A9,
    "SI-P01-B9": SI_P01_B9,
    "SI-P01-C9": SI_P01_C9,
    "SI-P01-D9": SI_P01_D9,
    "SI-P01-E9": SI_P01_E9,
    "SI-P01-F9": SI_P01_F9,
    "SI-P01-G9": SI_P01_G9,
    "SI-P01-H9": SI_P01_H9,
    "SI-P01-A10": SI_P01_A10,
    "SI-P01-B10": SI_P01_B10,
    "SI-P01-C10": SI_P01_C10,
    "SI-P01-D10": SI_P01_D10,
    "SI-P01-E10": SI_P01_E10,
    "SI-P01-F10": SI_P01_F10,
    "SI-P01-G10": SI_P01_G10,
    "SI-P01-H10": SI_P01_H10,
    "SI-P01-A11": SI_P01_A11,
    "SI-P01-B11": SI_P01_B11,
    "SI-P01-C11": SI_P01_C11,
    "SI-P01-D11": SI_P01_D11,
    "SI-P01-E11": SI_P01_E11,
    "SI-P01-F11": SI_P01_F11,
    "SI-P01-G11": SI_P01_G11,
    "SI-P01-H11": SI_P01_H11,
    "SI-P01-A12": SI_P01_A12,
    "SI-P01-B12": SI_P01_B12,
    "SI-P01-C12": SI_P01_C12,
    "SI-P01-D12": SI_P01_D12,
    "SI-P01-E12": SI_P01_E12,
    "SI-P01-F12": SI_P01_F12,
    "SI-P01-G12": SI_P01_G12,
    "SI-P01-H12": SI_P01_H12,
    "SI-P03-A1": SI_P03_A1,
    "SI-P03-B1": SI_P03_B1,
    "SI-P03-C1": SI_P03_C1,
    "SI-P03-D1": SI_P03_D1,
    "SI-P03-E1": SI_P03_E1,
    "SI-P03-F1": SI_P03_F1,
    "SI-P03-G1": SI_P03_G1,
    "SI-P03-H1": SI_P03_H1,
    "SI-P03-A2": SI_P03_A2,
    "SI-P03-B2": SI_P03_B2,
    "SI-P03-C2": SI_P03_C2,
    "SI-P03-D2": SI_P03_D2,
    "SI-P03-E2": SI_P03_E2,
    "SI-P03-F2": SI_P03_F2,
    "SI-P03-G2": SI_P03_G2,
    "SI-P03-H2": SI_P03_H2,
    "SI-P03-A3": SI_P03_A3,
    "SI-P03-B3": SI_P03_B3,
    "SI-P03-C3": SI_P03_C3,
    "SI-P03-D3": SI_P03_D3,
    "SI-P03-E3": SI_P03_E3,
    "SI-P03-F3": SI_P03_F3,
    "SI-P03-G3": SI_P03_G3,
    "SI-P03-H3": SI_P03_H3,
    "SI-P03-A4": SI_P03_A4,
    "SI-P03-B4": SI_P03_B4,
    "SI-P03-C4": SI_P03_C4,
    "SI-P03-D4": SI_P03_D4,
    "SI-P03-E4": SI_P03_E4,
    "SI-P03-F4": SI_P03_F4,
    "SI-P03-G4": SI_P03_G4,
    "SI-P03-H4": SI_P03_H4,
    "SI-P03-A5": SI_P03_A5,
    "SI-P03-B5": SI_P03_B5,
    "SI-P03-C5": SI_P03_C5,
    "SI-P03-D5": SI_P03_D5,
    "SI-P03-E5": SI_P03_E5,
    "SI-P03-F5": SI_P03_F5,
    "SI-P03-G5": SI_P03_G5,
    "SI-P03-H5": SI_P03_H5,
    "SI-P03-A6": SI_P03_A6,
    "SI-P03-B6": SI_P03_B6,
    "SI-P03-C6": SI_P03_C6,
    "SI-P03-D6": SI_P03_D6,
    "SI-P03-E6": SI_P03_E6,
    "SI-P03-F6": SI_P03_F6,
    "SI-P03-G6": SI_P03_G6,
    "SI-P03-H6": SI_P03_H6,
    "SI-P03-A7": SI_P03_A7,
    "SI-P03-B7": SI_P03_B7,
    "SI-P03-C7": SI_P03_C7,
    "SI-P03-D7": SI_P03_D7,
    "SI-P03-E7": SI_P03_E7,
    "SI-P03-F7": SI_P03_F7,
    "SI-P03-G7": SI_P03_G7,
    "SI-P03-H7": SI_P03_H7,
    "SI-P03-A8": SI_P03_A8,
    "SI-P03-B8": SI_P03_B8,
    "SI-P03-C8": SI_P03_C8,
    "SI-P03-D8": SI_P03_D8,
    "SI-P03-E8": SI_P03_E8,
    "SI-P03-F8": SI_P03_F8,
    "SI-P03-G8": SI_P03_G8,
    "SI-P03-H8": SI_P03_H8,
    "SI-P03-A9": SI_P03_A9,
    "SI-P03-B9": SI_P03_B9,
    "SI-P03-C9": SI_P03_C9,
    "SI-P03-D9": SI_P03_D9,
    "SI-P03-E9": SI_P03_E9,
    "SI-P03-F9": SI_P03_F9,
    "SI-P03-G9": SI_P03_G9,
    "SI-P03-H9": SI_P03_H9,
    "SI-P03-A10": SI_P03_A10,
    "SI-P03-B10": SI_P03_B10,
    "SI-P03-C10": SI_P03_C10,
    "SI-P03-D10": SI_P03_D10,
    "SI-P03-E10": SI_P03_E10,
    "SI-P03-F10": SI_P03_F10,
    "SI-P03-G10": SI_P03_G10,
    "SI-P03-H10": SI_P03_H10,
    "SI-P03-A11": SI_P03_A11,
    "SI-P03-B11": SI_P03_B11,
    "SI-P03-C11": SI_P03_C11,
    "SI-P03-D11": SI_P03_D11,
    "SI-P03-E11": SI_P03_E11,
    "SI-P03-F11": SI_P03_F11,
    "SI-P03-G11": SI_P03_G11,
    "SI-P03-H11": SI_P03_H11,
    "SI-P03-A12": SI_P03_A12,
    "SI-P03-B12": SI_P03_B12,
    "SI-P03-C12": SI_P03_C12,
    "SI-P03-D12": SI_P03_D12,
    "SI-P03-E12": SI_P03_E12,
    "SI-P03-F12": SI_P03_F12,
    "SI-P03-G12": SI_P03_G12,
    "SI-P03-H12": SI_P03_H12,
    "SI-3A-A1": SI_3A_A1,
    "SI-3A-B1": SI_3A_B1,
    "SI-3A-C1": SI_3A_C1,
    "SI-3A-D1": SI_3A_D1,
    "SI-3A-E1": SI_3A_E1,
    "SI-3A-F1": SI_3A_F1,
    "SI-3A-G1": SI_3A_G1,
    "SI-3A-H1": SI_3A_H1,
    "SI-3A-A2": SI_3A_A2,
    "SI-3A-B2": SI_3A_B2,
    "SI-3A-C2": SI_3A_C2,
    "SI-3A-D2": SI_3A_D2,
    "SI-3A-E2": SI_3A_E2,
    "SI-3A-F2": SI_3A_F2,
    "SI-3A-G2": SI_3A_G2,
    "SI-3A-H2": SI_3A_H2,
    "SI-3A-A3": SI_3A_A3,
    "SI-3A-B3": SI_3A_B3,
    "SI-3A-C3": SI_3A_C3,
    "SI-3A-D3": SI_3A_D3,
    "SI-3A-E3": SI_3A_E3,
    "SI-3A-F3": SI_3A_F3,
    "SI-3A-G3": SI_3A_G3,
    "SI-3A-H3": SI_3A_H3,
    "SI-3A-A4": SI_3A_A4,
    "SI-3A-B4": SI_3A_B4,
    "SI-3A-C4": SI_3A_C4,
    "SI-3A-D4": SI_3A_D4,
    "SI-3A-E4": SI_3A_E4,
    "SI-3A-F4": SI_3A_F4,
    "SI-3A-G4": SI_3A_G4,
    "SI-3A-H4": SI_3A_H4,
    "SI-3A-A5": SI_3A_A5,
    "SI-3A-B5": SI_3A_B5,
    "SI-3A-C5": SI_3A_C5,
    "SI-3A-D5": SI_3A_D5,
    "SI-3A-E5": SI_3A_E5,
    "SI-3A-F5": SI_3A_F5,
    "SI-3A-G5": SI_3A_G5,
    "SI-3A-H5": SI_3A_H5,
    "SI-3A-A6": SI_3A_A6,
    "SI-3A-B6": SI_3A_B6,
    "SI-3A-C6": SI_3A_C6,
    "SI-3A-D6": SI_3A_D6,
    "SI-3A-E6": SI_3A_E6,
    "SI-3A-F6": SI_3A_F6,
    "SI-3A-G6": SI_3A_G6,
    "SI-3A-H6": SI_3A_H6,
    "SI-3A-A7": SI_3A_A7,
    "SI-3A-B7": SI_3A_B7,
    "SI-3A-C7": SI_3A_C7,
    "SI-3A-D7": SI_3A_D7,
    "SI-3A-E7": SI_3A_E7,
    "SI-3A-F7": SI_3A_F7,
    "SI-3A-G7": SI_3A_G7,
    "SI-3A-H7": SI_3A_H7,
    "SI-3A-A8": SI_3A_A8,
    "SI-3A-B8": SI_3A_B8,
    "SI-3A-C8": SI_3A_C8,
    "SI-3A-D8": SI_3A_D8,
    "SI-3A-E8": SI_3A_E8,
    "SI-3A-F8": SI_3A_F8,
    "SI-3A-G8": SI_3A_G8,
    "SI-3A-H8": SI_3A_H8,
    "SI-3A-A9": SI_3A_A9,
    "SI-3A-B9": SI_3A_B9,
    "SI-3A-C9": SI_3A_C9,
    "SI-3A-D9": SI_3A_D9,
    "SI-3A-E9": SI_3A_E9,
    "SI-3A-F9": SI_3A_F9,
    "SI-3A-G9": SI_3A_G9,
    "SI-3A-H9": SI_3A_H9,
    "SI-3A-A10": SI_3A_A10,
    "SI-3A-B10": SI_3A_B10,
    "SI-3A-C10": SI_3A_C10,
    "SI-3A-D10": SI_3A_D10,
    "SI-3A-E10": SI_3A_E10,
    "SI-3A-F10": SI_3A_F10,
    "SI-3A-G10": SI_3A_G10,
    "SI-3A-H10": SI_3A_H10,
    "SI-3A-A11": SI_3A_A11,
    "SI-3A-B11": SI_3A_B11,
    "SI-3A-C11": SI_3A_C11,
    "SI-3A-D11": SI_3A_D11,
    "SI-3A-E11": SI_3A_E11,
    "SI-3A-F11": SI_3A_F11,
    "SI-3A-G11": SI_3A_G11,
    "SI-3A-H11": SI_3A_H11,
    "SI-3A-A12": SI_3A_A12,
    "SI-3A-B12": SI_3A_B12,
    "SI-3A-C12": SI_3A_C12,
    "SI-3A-D12": SI_3A_D12,
    "SI-3A-E12": SI_3A_E12,
    "SI-3A-F12": SI_3A_F12,
    "SI-3A-G12": SI_3A_G12,
    "SI-3A-H12": SI_3A_H12,
    "SI-GA-A1": SI_GA_A1,
    "SI-GA-B1": SI_GA_B1,
    "SI-GA-C1": SI_GA_C1,
    "SI-GA-D1": SI_GA_D1,
    "SI-GA-E1": SI_GA_E1,
    "SI-GA-F1": SI_GA_F1,
    "SI-GA-G1": SI_GA_G1,
    "SI-GA-H1": SI_GA_H1,
    "SI-GA-A2": SI_GA_A2,
    "SI-GA-B2": SI_GA_B2,
    "SI-GA-C2": SI_GA_C2,
    "SI-GA-D2": SI_GA_D2,
    "SI-GA-E2": SI_GA_E2,
    "SI-GA-F2": SI_GA_F2,
    "SI-GA-G2": SI_GA_G2,
    "SI-GA-H2": SI_GA_H2,
    "SI-GA-A3": SI_GA_A3,
    "SI-GA-B3": SI_GA_B3,
    "SI-GA-C3": SI_GA_C3,
    "SI-GA-D3": SI_GA_D3,
    "SI-GA-E3": SI_GA_E3,
    "SI-GA-F3": SI_GA_F3,
    "SI-GA-G3": SI_GA_G3,
    "SI-GA-H3": SI_GA_H3,
    "SI-GA-A4": SI_GA_A4,
    "SI-GA-B4": SI_GA_B4,
    "SI-GA-C4": SI_GA_C4,
    "SI-GA-D4": SI_GA_D4,
    "SI-GA-E4": SI_GA_E4,
    "SI-GA-F4": SI_GA_F4,
    "SI-GA-G4": SI_GA_G4,
    "SI-GA-H4": SI_GA_H4,
    "SI-GA-A5": SI_GA_A5,
    "SI-GA-B5": SI_GA_B5,
    "SI-GA-C5": SI_GA_C5,
    "SI-GA-D5": SI_GA_D5,
    "SI-GA-E5": SI_GA_E5,
    "SI-GA-F5": SI_GA_F5,
    "SI-GA-G5": SI_GA_G5,
    "SI-GA-H5": SI_GA_H5,
    "SI-GA-A6": SI_GA_A6,
    "SI-GA-B6": SI_GA_B6,
    "SI-GA-C6": SI_GA_C6,
    "SI-GA-D6": SI_GA_D6,
    "SI-GA-E6": SI_GA_E6,
    "SI-GA-F6": SI_GA_F6,
    "SI-GA-G6": SI_GA_G6,
    "SI-GA-H6": SI_GA_H6,
    "SI-GA-A7": SI_GA_A7,
    "SI-GA-B7": SI_GA_B7,
    "SI-GA-C7": SI_GA_C7,
    "SI-GA-D7": SI_GA_D7,
    "SI-GA-E7": SI_GA_E7,
    "SI-GA-F7": SI_GA_F7,
    "SI-GA-G7": SI_GA_G7,
    "SI-GA-H7": SI_GA_H7,
    "SI-GA-A8": SI_GA_A8,
    "SI-GA-B8": SI_GA_B8,
    "SI-GA-C8": SI_GA_C8,
    "SI-GA-D8": SI_GA_D8,
    "SI-GA-E8": SI_GA_E8,
    "SI-GA-F8": SI_GA_F8,
    "SI-GA-G8": SI_GA_G8,
    "SI-GA-H8": SI_GA_H8,
    "SI-GA-A9": SI_GA_A9,
    "SI-GA-B9": SI_GA_B9,
    "SI-GA-C9": SI_GA_C9,
    "SI-GA-D9": SI_GA_D9,
    "SI-GA-E9": SI_GA_E9,
    "SI-GA-F9": SI_GA_F9,
    "SI-GA-G9": SI_GA_G9,
    "SI-GA-H9": SI_GA_H9,
    "SI-GA-A10": SI_GA_A10,
    "SI-GA-B10": SI_GA_B10,
    "SI-GA-C10": SI_GA_C10,
    "SI-GA-D10": SI_GA_D10,
    "SI-GA-E10": SI_GA_E10,
    "SI-GA-F10": SI_GA_F10,
    "SI-GA-G10": SI_GA_G10,
    "SI-GA-H10": SI_GA_H10,
    "SI-GA-A11": SI_GA_A11,
    "SI-GA-B11": SI_GA_B11,
    "SI-GA-C11": SI_GA_C11,
    "SI-GA-D11": SI_GA_D11,
    "SI-GA-E11": SI_GA_E11,
    "SI-GA-F11": SI_GA_F11,
    "SI-GA-G11": SI_GA_G11,
    "SI-GA-H11": SI_GA_H11,
    "SI-GA-A12": SI_GA_A12,
    "SI-GA-B12": SI_GA_B12,
    "SI-GA-C12": SI_GA_C12,
    "SI-GA-D12": SI_GA_D12,
    "SI-GA-E12": SI_GA_E12,
    "SI-GA-F12": SI_GA_F12,
    "SI-GA-G12": SI_GA_G12,
    "SI-GA-H12": SI_GA_H12,
    # ATAC/VDJ-FB
    "SI-NA-A1": SI_NA_A1,
    "SI-NA-B1": SI_NA_B1,
    "SI-NA-C1": SI_NA_C1,
    "SI-NA-D1": SI_NA_D1,
    "SI-NA-E1": SI_NA_E1,
    "SI-NA-F1": SI_NA_F1,
    "SI-NA-G1": SI_NA_G1,
    "SI-NA-H1": SI_NA_H1,
    "SI-NA-A2": SI_NA_A2,
    "SI-NA-B2": SI_NA_B2,
    "SI-NA-C2": SI_NA_C2,
    "SI-NA-D2": SI_NA_D2,
    "SI-NA-E2": SI_NA_E2,
    "SI-NA-F2": SI_NA_F2,
    "SI-NA-G2": SI_NA_G2,
    "SI-NA-H2": SI_NA_H2,
    "SI-NA-A3": SI_NA_A3,
    "SI-NA-B3": SI_NA_B3,
    "SI-NA-C3": SI_NA_C3,
    "SI-NA-D3": SI_NA_D3,
    "SI-NA-E3": SI_NA_E3,
    "SI-NA-F3": SI_NA_F3,
    "SI-NA-G3": SI_NA_G3,
    "SI-NA-H3": SI_NA_H3,
    "SI-NA-A4": SI_NA_A4,
    "SI-NA-B4": SI_NA_B4,
    "SI-NA-C4": SI_NA_C4,
    "SI-NA-D4": SI_NA_D4,
    "SI-NA-E4": SI_NA_E4,
    "SI-NA-F4": SI_NA_F4,
    "SI-NA-G4": SI_NA_G4,
    "SI-NA-H4": SI_NA_H4,
    "SI-NA-A5": SI_NA_A5,
    "SI-NA-B5": SI_NA_B5,
    "SI-NA-C5": SI_NA_C5,
    "SI-NA-D5": SI_NA_D5,
    "SI-NA-E5": SI_NA_E5,
    "SI-NA-F5": SI_NA_F5,
    "SI-NA-G5": SI_NA_G5,
    "SI-NA-H5": SI_NA_H5,
    "SI-NA-A6": SI_NA_A6,
    "SI-NA-B6": SI_NA_B6,
    "SI-NA-C6": SI_NA_C6,
    "SI-NA-D6": SI_NA_D6,
    "SI-NA-E6": SI_NA_E6,
    "SI-NA-F6": SI_NA_F6,
    "SI-NA-G6": SI_NA_G6,
    "SI-NA-H6": SI_NA_H6,
    "SI-NA-A7": SI_NA_A7,
    "SI-NA-B7": SI_NA_B7,
    "SI-NA-C7": SI_NA_C7,
    "SI-NA-D7": SI_NA_D7,
    "SI-NA-E7": SI_NA_E7,
    "SI-NA-F7": SI_NA_F7,
    "SI-NA-G7": SI_NA_G7,
    "SI-NA-H7": SI_NA_H7,
    "SI-NA-A8": SI_NA_A8,
    "SI-NA-B8": SI_NA_B8,
    "SI-NA-C8": SI_NA_C8,
    "SI-NA-D8": SI_NA_D8,
    "SI-NA-E8": SI_NA_E8,
    "SI-NA-F8": SI_NA_F8,
    "SI-NA-G8": SI_NA_G8,
    "SI-NA-H8": SI_NA_H8,
    "SI-NA-A9": SI_NA_A9,
    "SI-NA-B9": SI_NA_B9,
    "SI-NA-C9": SI_NA_C9,
    "SI-NA-D9": SI_NA_D9,
    "SI-NA-E9": SI_NA_E9,
    "SI-NA-F9": SI_NA_F9,
    "SI-NA-G9": SI_NA_G9,
    "SI-NA-H9": SI_NA_H9,
    "SI-NA-A10": SI_NA_A10,
    "SI-NA-B10": SI_NA_B10,
    "SI-NA-C10": SI_NA_C10,
    "SI-NA-D10": SI_NA_D10,
    "SI-NA-E10": SI_NA_E10,
    "SI-NA-F10": SI_NA_F10,
    "SI-NA-G10": SI_NA_G10,
    "SI-NA-H10": SI_NA_H10,
    "SI-NA-A11": SI_NA_A11,
    "SI-NA-B11": SI_NA_B11,
    "SI-NA-C11": SI_NA_C11,
    "SI-NA-D11": SI_NA_D11,
    "SI-NA-E11": SI_NA_E11,
    "SI-NA-F11": SI_NA_F11,
    "SI-NA-G11": SI_NA_G11,
    "SI-NA-H11": SI_NA_H11,
    "SI-NA-A12": SI_NA_A12,
    "SI-NA-B12": SI_NA_B12,
    "SI-NA-C12": SI_NA_C12,
    "SI-NA-D12": SI_NA_D12,
    "SI-NA-E12": SI_NA_E12,
    "SI-NA-F12": SI_NA_F12,
    "SI-NA-G12": SI_NA_G12,
    "SI-NA-H12": SI_NA_H12,
    # GemCode Part numbers
    "220027": SI_001,
    "220028": SI_002,
    "220029": SI_003,
    "220030": SI_004,
    "220031": SI_005,
    "220032": SI_006,
    "220033": SI_007,
    "220034": SI_008,
    # WGS+ Tube labels
    "SI-T2-1": SI_T2_1,
    "SI-T2-2": SI_T2_2,
    "SI-T2-3": SI_T2_3,
    "SI-T2-4": SI_T2_4,
    "SI-T2-5": SI_T2_5,
    "SI-T2-6": SI_T2_6,
    "SI-T2-7": SI_T2_7,
    "SI-T2-8": SI_T2_8,
    # WGS+ Plate labels
    "SI-P2-A1": SI_P2_A1,
    "SI-P2-A2": SI_P2_A2,
    "SI-P2-A3": SI_P2_A3,
    "SI-P2-A4": SI_P2_A4,
    "SI-P2-A5": SI_P2_A5,
    "SI-P2-A6": SI_P2_A6,
    "SI-P2-A7": SI_P2_A7,
    "SI-P2-A8": SI_P2_A8,
    "SI-P2-A9": SI_P2_A9,
    "SI-P2-A10": SI_P2_A10,
    "SI-P2-A11": SI_P2_A11,
    "SI-P2-A12": SI_P2_A12,
    "SI-P2-B1": SI_P2_B1,
    "SI-P2-B2": SI_P2_B2,
    "SI-P2-B3": SI_P2_B3,
    "SI-P2-B4": SI_P2_B4,
    "SI-P2-B5": SI_P2_B5,
    "SI-P2-B6": SI_P2_B6,
    "SI-P2-B7": SI_P2_B7,
    "SI-P2-B8": SI_P2_B8,
    "SI-P2-B9": SI_P2_B9,
    "SI-P2-B10": SI_P2_B10,
    "SI-P2-B11": SI_P2_B11,
    "SI-P2-B12": SI_P2_B12,
    "SI-P2-C1": SI_P2_C1,
    "SI-P2-C2": SI_P2_C2,
    "SI-P2-C3": SI_P2_C3,
    "SI-P2-C4": SI_P2_C4,
    "SI-P2-C5": SI_P2_C5,
    "SI-P2-C6": SI_P2_C6,
    "SI-P2-C7": SI_P2_C7,
    "SI-P2-C8": SI_P2_C8,
    "SI-P2-C9": SI_P2_C9,
    "SI-P2-C10": SI_P2_C10,
    "SI-P2-C11": SI_P2_C11,
    "SI-P2-C12": SI_P2_C12,
    "SI-P2-D1": SI_P2_D1,
    "SI-P2-D2": SI_P2_D2,
    "SI-P2-D3": SI_P2_D3,
    "SI-P2-D4": SI_P2_D4,
    "SI-P2-D5": SI_P2_D5,
    "SI-P2-D6": SI_P2_D6,
    "SI-P2-D7": SI_P2_D7,
    "SI-P2-D8": SI_P2_D8,
    "SI-P2-D9": SI_P2_D9,
    "SI-P2-D10": SI_P2_D10,
    "SI-P2-D11": SI_P2_D11,
    "SI-P2-D12": SI_P2_D12,
    "SI-P2-E1": SI_P2_E1,
    "SI-P2-E2": SI_P2_E2,
    "SI-P2-E3": SI_P2_E3,
    "SI-P2-E4": SI_P2_E4,
    "SI-P2-E5": SI_P2_E5,
    "SI-P2-E6": SI_P2_E6,
    "SI-P2-E7": SI_P2_E7,
    "SI-P2-E8": SI_P2_E8,
    "SI-P2-E9": SI_P2_E9,
    "SI-P2-E10": SI_P2_E10,
    "SI-P2-E11": SI_P2_E11,
    "SI-P2-E12": SI_P2_E12,
    "SI-P2-F1": SI_P2_F1,
    "SI-P2-F2": SI_P2_F2,
    "SI-P2-F3": SI_P2_F3,
    "SI-P2-F4": SI_P2_F4,
    "SI-P2-F5": SI_P2_F5,
    "SI-P2-F6": SI_P2_F6,
    "SI-P2-F7": SI_P2_F7,
    "SI-P2-F8": SI_P2_F8,
    "SI-P2-F9": SI_P2_F9,
    "SI-P2-F10": SI_P2_F10,
    "SI-P2-F11": SI_P2_F11,
    "SI-P2-F12": SI_P2_F12,
    "SI-P2-G1": SI_P2_G1,
    "SI-P2-G2": SI_P2_G2,
    "SI-P2-G3": SI_P2_G3,
    "SI-P2-G4": SI_P2_G4,
    "SI-P2-G5": SI_P2_G5,
    "SI-P2-G6": SI_P2_G6,
    "SI-P2-G7": SI_P2_G7,
    "SI-P2-G8": SI_P2_G8,
    "SI-P2-G9": SI_P2_G9,
    "SI-P2-G10": SI_P2_G10,
    "SI-P2-G11": SI_P2_G11,
    "SI-P2-G12": SI_P2_G12,
    "SI-P2-H1": SI_P2_H1,
    "SI-P2-H2": SI_P2_H2,
    "SI-P2-H3": SI_P2_H3,
    "SI-P2-H4": SI_P2_H4,
    "SI-P2-H5": SI_P2_H5,
    "SI-P2-H6": SI_P2_H6,
    "SI-P2-H7": SI_P2_H7,
    "SI-P2-H8": SI_P2_H8,
    "SI-P2-H9": SI_P2_H9,
    "SI-P2-H10": SI_P2_H10,
    "SI-P2-H11": SI_P2_H11,
    "SI-P2-H12": SI_P2_H12,
    # WGS+ Plate Label 10bp
    "SI-P2-A1-10bp": SI_P2_A1_10bp,
    "SI-P2-A2-10bp": SI_P2_A2_10bp,
    "SI-P2-A3-10bp": SI_P2_A3_10bp,
    "SI-P2-A4-10bp": SI_P2_A4_10bp,
    "SI-P2-A5-10bp": SI_P2_A5_10bp,
    "SI-P2-A6-10bp": SI_P2_A6_10bp,
    "SI-P2-A7-10bp": SI_P2_A7_10bp,
    "SI-P2-A8-10bp": SI_P2_A8_10bp,
    "SI-P2-A9-10bp": SI_P2_A9_10bp,
    "SI-P2-A10-10bp": SI_P2_A10_10bp,
    "SI-P2-A11-10bp": SI_P2_A11_10bp,
    "SI-P2-A12-10bp": SI_P2_A12_10bp,
    "SI-P2-B1-10bp": SI_P2_B1_10bp,
    "SI-P2-B2-10bp": SI_P2_B2_10bp,
    "SI-P2-B3-10bp": SI_P2_B3_10bp,
    "SI-P2-B4-10bp": SI_P2_B4_10bp,
    "SI-P2-B5-10bp": SI_P2_B5_10bp,
    "SI-P2-B6-10bp": SI_P2_B6_10bp,
    "SI-P2-B7-10bp": SI_P2_B7_10bp,
    "SI-P2-B8-10bp": SI_P2_B8_10bp,
    "SI-P2-B9-10bp": SI_P2_B9_10bp,
    "SI-P2-B10-10bp": SI_P2_B10_10bp,
    "SI-P2-B11-10bp": SI_P2_B11_10bp,
    "SI-P2-B12-10bp": SI_P2_B12_10bp,
    "SI-P2-C1-10bp": SI_P2_C1_10bp,
    "SI-P2-C2-10bp": SI_P2_C2_10bp,
    "SI-P2-C3-10bp": SI_P2_C3_10bp,
    "SI-P2-C4-10bp": SI_P2_C4_10bp,
    "SI-P2-C5-10bp": SI_P2_C5_10bp,
    "SI-P2-C6-10bp": SI_P2_C6_10bp,
    "SI-P2-C7-10bp": SI_P2_C7_10bp,
    "SI-P2-C8-10bp": SI_P2_C8_10bp,
    "SI-P2-C9-10bp": SI_P2_C9_10bp,
    "SI-P2-C10-10bp": SI_P2_C10_10bp,
    "SI-P2-C11-10bp": SI_P2_C11_10bp,
    "SI-P2-C12-10bp": SI_P2_C12_10bp,
    "SI-P2-D1-10bp": SI_P2_D1_10bp,
    "SI-P2-D2-10bp": SI_P2_D2_10bp,
    "SI-P2-D3-10bp": SI_P2_D3_10bp,
    "SI-P2-D4-10bp": SI_P2_D4_10bp,
    "SI-P2-D5-10bp": SI_P2_D5_10bp,
    "SI-P2-D6-10bp": SI_P2_D6_10bp,
    "SI-P2-D7-10bp": SI_P2_D7_10bp,
    "SI-P2-D8-10bp": SI_P2_D8_10bp,
    "SI-P2-D9-10bp": SI_P2_D9_10bp,
    "SI-P2-D10-10bp": SI_P2_D10_10bp,
    "SI-P2-D11-10bp": SI_P2_D11_10bp,
    "SI-P2-D12-10bp": SI_P2_D12_10bp,
    "SI-P2-E1-10bp": SI_P2_E1_10bp,
    "SI-P2-E2-10bp": SI_P2_E2_10bp,
    "SI-P2-E3-10bp": SI_P2_E3_10bp,
    "SI-P2-E4-10bp": SI_P2_E4_10bp,
    "SI-P2-E5-10bp": SI_P2_E5_10bp,
    "SI-P2-E6-10bp": SI_P2_E6_10bp,
    "SI-P2-E7-10bp": SI_P2_E7_10bp,
    "SI-P2-E8-10bp": SI_P2_E8_10bp,
    "SI-P2-E9-10bp": SI_P2_E9_10bp,
    "SI-P2-E10-10bp": SI_P2_E10_10bp,
    "SI-P2-E11-10bp": SI_P2_E11_10bp,
    "SI-P2-E12-10bp": SI_P2_E12_10bp,
    "SI-P2-F1-10bp": SI_P2_F1_10bp,
    "SI-P2-F2-10bp": SI_P2_F2_10bp,
    "SI-P2-F3-10bp": SI_P2_F3_10bp,
    "SI-P2-F4-10bp": SI_P2_F4_10bp,
    "SI-P2-F5-10bp": SI_P2_F5_10bp,
    "SI-P2-F6-10bp": SI_P2_F6_10bp,
    "SI-P2-F7-10bp": SI_P2_F7_10bp,
    "SI-P2-F8-10bp": SI_P2_F8_10bp,
    "SI-P2-F9-10bp": SI_P2_F9_10bp,
    "SI-P2-F10-10bp": SI_P2_F10_10bp,
    "SI-P2-F11-10bp": SI_P2_F11_10bp,
    "SI-P2-F12-10bp": SI_P2_F12_10bp,
    "SI-P2-G1-10bp": SI_P2_G1_10bp,
    "SI-P2-G2-10bp": SI_P2_G2_10bp,
    "SI-P2-G3-10bp": SI_P2_G3_10bp,
    "SI-P2-G4-10bp": SI_P2_G4_10bp,
    "SI-P2-G5-10bp": SI_P2_G5_10bp,
    "SI-P2-G6-10bp": SI_P2_G6_10bp,
    "SI-P2-G7-10bp": SI_P2_G7_10bp,
    "SI-P2-G8-10bp": SI_P2_G8_10bp,
    "SI-P2-G9-10bp": SI_P2_G9_10bp,
    "SI-P2-G10-10bp": SI_P2_G10_10bp,
    "SI-P2-G11-10bp": SI_P2_G11_10bp,
    "SI-P2-G12-10bp": SI_P2_G12_10bp,
    "SI-P2-H1-10bp": SI_P2_H1_10bp,
    "SI-P2-H2-10bp": SI_P2_H2_10bp,
    "SI-P2-H3-10bp": SI_P2_H3_10bp,
    "SI-P2-H4-10bp": SI_P2_H4_10bp,
    "SI-P2-H5-10bp": SI_P2_H5_10bp,
    "SI-P2-H6-10bp": SI_P2_H6_10bp,
    "SI-P2-H7-10bp": SI_P2_H7_10bp,
    "SI-P2-H8-10bp": SI_P2_H8_10bp,
    "SI-P2-H9-10bp": SI_P2_H9_10bp,
    "SI-P2-H10-10bp": SI_P2_H10_10bp,
    "SI-P2-H11-10bp": SI_P2_H11_10bp,
    "SI-P2-H12-10bp": SI_P2_H12_10bp,
    # WGS+ Plate Label alternate
    "SI-P02-A1": SI_P2_A1,
    "SI-P02-A2": SI_P2_A2,
    "SI-P02-A3": SI_P2_A3,
    "SI-P02-A4": SI_P2_A4,
    "SI-P02-A5": SI_P2_A5,
    "SI-P02-A6": SI_P2_A6,
    "SI-P02-A7": SI_P2_A7,
    "SI-P02-A8": SI_P2_A8,
    "SI-P02-A9": SI_P2_A9,
    "SI-P02-A10": SI_P2_A10,
    "SI-P02-A11": SI_P2_A11,
    "SI-P02-A12": SI_P2_A12,
    "SI-P02-B1": SI_P2_B1,
    "SI-P02-B2": SI_P2_B2,
    "SI-P02-B3": SI_P2_B3,
    "SI-P02-B4": SI_P2_B4,
    "SI-P02-B5": SI_P2_B5,
    "SI-P02-B6": SI_P2_B6,
    "SI-P02-B7": SI_P2_B7,
    "SI-P02-B8": SI_P2_B8,
    "SI-P02-B9": SI_P2_B9,
    "SI-P02-B10": SI_P2_B10,
    "SI-P02-B11": SI_P2_B11,
    "SI-P02-B12": SI_P2_B12,
    "SI-P02-C1": SI_P2_C1,
    "SI-P02-C2": SI_P2_C2,
    "SI-P02-C3": SI_P2_C3,
    "SI-P02-C4": SI_P2_C4,
    "SI-P02-C5": SI_P2_C5,
    "SI-P02-C6": SI_P2_C6,
    "SI-P02-C7": SI_P2_C7,
    "SI-P02-C8": SI_P2_C8,
    "SI-P02-C9": SI_P2_C9,
    "SI-P02-C10": SI_P2_C10,
    "SI-P02-C11": SI_P2_C11,
    "SI-P02-C12": SI_P2_C12,
    "SI-P02-D1": SI_P2_D1,
    "SI-P02-D2": SI_P2_D2,
    "SI-P02-D3": SI_P2_D3,
    "SI-P02-D4": SI_P2_D4,
    "SI-P02-D5": SI_P2_D5,
    "SI-P02-D6": SI_P2_D6,
    "SI-P02-D7": SI_P2_D7,
    "SI-P02-D8": SI_P2_D8,
    "SI-P02-D9": SI_P2_D9,
    "SI-P02-D10": SI_P2_D10,
    "SI-P02-D11": SI_P2_D11,
    "SI-P02-D12": SI_P2_D12,
    "SI-P02-E1": SI_P2_E1,
    "SI-P02-E2": SI_P2_E2,
    "SI-P02-E3": SI_P2_E3,
    "SI-P02-E4": SI_P2_E4,
    "SI-P02-E5": SI_P2_E5,
    "SI-P02-E6": SI_P2_E6,
    "SI-P02-E7": SI_P2_E7,
    "SI-P02-E8": SI_P2_E8,
    "SI-P02-E9": SI_P2_E9,
    "SI-P02-E10": SI_P2_E10,
    "SI-P02-E11": SI_P2_E11,
    "SI-P02-E12": SI_P2_E12,
    "SI-P02-F1": SI_P2_F1,
    "SI-P02-F2": SI_P2_F2,
    "SI-P02-F3": SI_P2_F3,
    "SI-P02-F4": SI_P2_F4,
    "SI-P02-F5": SI_P2_F5,
    "SI-P02-F6": SI_P2_F6,
    "SI-P02-F7": SI_P2_F7,
    "SI-P02-F8": SI_P2_F8,
    "SI-P02-F9": SI_P2_F9,
    "SI-P02-F10": SI_P2_F10,
    "SI-P02-F11": SI_P2_F11,
    "SI-P02-F12": SI_P2_F12,
    "SI-P02-G1": SI_P2_G1,
    "SI-P02-G2": SI_P2_G2,
    "SI-P02-G3": SI_P2_G3,
    "SI-P02-G4": SI_P2_G4,
    "SI-P02-G5": SI_P2_G5,
    "SI-P02-G6": SI_P2_G6,
    "SI-P02-G7": SI_P2_G7,
    "SI-P02-G8": SI_P2_G8,
    "SI-P02-G9": SI_P2_G9,
    "SI-P02-G10": SI_P2_G10,
    "SI-P02-G11": SI_P2_G11,
    "SI-P02-G12": SI_P2_G12,
    "SI-P02-H1": SI_P2_H1,
    "SI-P02-H2": SI_P2_H2,
    "SI-P02-H3": SI_P2_H3,
    "SI-P02-H4": SI_P2_H4,
    "SI-P02-H5": SI_P2_H5,
    "SI-P02-H6": SI_P2_H6,
    "SI-P02-H7": SI_P2_H7,
    "SI-P02-H8": SI_P2_H8,
    "SI-P02-H9": SI_P2_H9,
    "SI-P02-H10": SI_P2_H10,
    "SI-P02-H11": SI_P2_H11,
    "SI-P02-H12": SI_P2_H12,
    # T1T2 (used single ended by QC)
    **{
        sys.intern(f"SI-TT-{c}{i}"): globals()[f"SI_TT_{c}{i}"]
        for i in range(1, 13)
        for c in "ABCDEFGH"
    },
}

SAMPLE_SINGLE_INDEX_MAP = SAMPLE_INDEX_MAP

SAMPLE_DUAL_INDEX_MAP = {
    # T1T2 (shipping with SR 1.0)
    "SI-TT-A1": SI_TT_A1,
    "SI-TT-A2": SI_TT_A2,
    "SI-TT-A3": SI_TT_A3,
    "SI-TT-A4": SI_TT_A4,
    "SI-TT-A5": SI_TT_A5,
    "SI-TT-A6": SI_TT_A6,
    "SI-TT-A7": SI_TT_A7,
    "SI-TT-A8": SI_TT_A8,
    "SI-TT-A9": SI_TT_A9,
    "SI-TT-A10": SI_TT_A10,
    "SI-TT-A11": SI_TT_A11,
    "SI-TT-A12": SI_TT_A12,
    "SI-TT-B1": SI_TT_B1,
    "SI-TT-B2": SI_TT_B2,
    "SI-TT-B3": SI_TT_B3,
    "SI-TT-B4": SI_TT_B4,
    "SI-TT-B5": SI_TT_B5,
    "SI-TT-B6": SI_TT_B6,
    "SI-TT-B7": SI_TT_B7,
    "SI-TT-B8": SI_TT_B8,
    "SI-TT-B9": SI_TT_B9,
    "SI-TT-B10": SI_TT_B10,
    "SI-TT-B11": SI_TT_B11,
    "SI-TT-B12": SI_TT_B12,
    "SI-TT-C1": SI_TT_C1,
    "SI-TT-C2": SI_TT_C2,
    "SI-TT-C3": SI_TT_C3,
    "SI-TT-C4": SI_TT_C4,
    "SI-TT-C5": SI_TT_C5,
    "SI-TT-C6": SI_TT_C6,
    "SI-TT-C7": SI_TT_C7,
    "SI-TT-C8": SI_TT_C8,
    "SI-TT-C9": SI_TT_C9,
    "SI-TT-C10": SI_TT_C10,
    "SI-TT-C11": SI_TT_C11,
    "SI-TT-C12": SI_TT_C12,
    "SI-TT-D1": SI_TT_D1,
    "SI-TT-D2": SI_TT_D2,
    "SI-TT-D3": SI_TT_D3,
    "SI-TT-D4": SI_TT_D4,
    "SI-TT-D5": SI_TT_D5,
    "SI-TT-D6": SI_TT_D6,
    "SI-TT-D7": SI_TT_D7,
    "SI-TT-D8": SI_TT_D8,
    "SI-TT-D9": SI_TT_D9,
    "SI-TT-D10": SI_TT_D10,
    "SI-TT-D11": SI_TT_D11,
    "SI-TT-D12": SI_TT_D12,
    "SI-TT-E1": SI_TT_E1,
    "SI-TT-E2": SI_TT_E2,
    "SI-TT-E3": SI_TT_E3,
    "SI-TT-E4": SI_TT_E4,
    "SI-TT-E5": SI_TT_E5,
    "SI-TT-E6": SI_TT_E6,
    "SI-TT-E7": SI_TT_E7,
    "SI-TT-E8": SI_TT_E8,
    "SI-TT-E9": SI_TT_E9,
    "SI-TT-E10": SI_TT_E10,
    "SI-TT-E11": SI_TT_E11,
    "SI-TT-E12": SI_TT_E12,
    "SI-TT-F1": SI_TT_F1,
    "SI-TT-F2": SI_TT_F2,
    "SI-TT-F3": SI_TT_F3,
    "SI-TT-F4": SI_TT_F4,
    "SI-TT-F5": SI_TT_F5,
    "SI-TT-F6": SI_TT_F6,
    "SI-TT-F7": SI_TT_F7,
    "SI-TT-F8": SI_TT_F8,
    "SI-TT-F9": SI_TT_F9,
    "SI-TT-F10": SI_TT_F10,
    "SI-TT-F11": SI_TT_F11,
    "SI-TT-F12": SI_TT_F12,
    "SI-TT-G1": SI_TT_G1,
    "SI-TT-G2": SI_TT_G2,
    "SI-TT-G3": SI_TT_G3,
    "SI-TT-G4": SI_TT_G4,
    "SI-TT-G5": SI_TT_G5,
    "SI-TT-G6": SI_TT_G6,
    "SI-TT-G7": SI_TT_G7,
    "SI-TT-G8": SI_TT_G8,
    "SI-TT-G9": SI_TT_G9,
    "SI-TT-G10": SI_TT_G10,
    "SI-TT-G11": SI_TT_G11,
    "SI-TT-G12": SI_TT_G12,
    "SI-TT-H1": SI_TT_H1,
    "SI-TT-H2": SI_TT_H2,
    "SI-TT-H3": SI_TT_H3,
    "SI-TT-H4": SI_TT_H4,
    "SI-TT-H5": SI_TT_H5,
    "SI-TT-H6": SI_TT_H6,
    "SI-TT-H7": SI_TT_H7,
    "SI-TT-H8": SI_TT_H8,
    "SI-TT-H9": SI_TT_H9,
    "SI-TT-H10": SI_TT_H10,
    "SI-TT-H11": SI_TT_H11,
    "SI-TT-H12": SI_TT_H12,
    "SI-TN-A1": SI_TN_A1,
    "SI-TN-A2": SI_TN_A2,
    "SI-TN-A3": SI_TN_A3,
    "SI-TN-A4": SI_TN_A4,
    "SI-TN-A5": SI_TN_A5,
    "SI-TN-A6": SI_TN_A6,
    "SI-TN-A7": SI_TN_A7,
    "SI-TN-A8": SI_TN_A8,
    "SI-TN-A9": SI_TN_A9,
    "SI-TN-A10": SI_TN_A10,
    "SI-TN-A11": SI_TN_A11,
    "SI-TN-A12": SI_TN_A12,
    "SI-TN-B1": SI_TN_B1,
    "SI-TN-B2": SI_TN_B2,
    "SI-TN-B3": SI_TN_B3,
    "SI-TN-B4": SI_TN_B4,
    "SI-TN-B5": SI_TN_B5,
    "SI-TN-B6": SI_TN_B6,
    "SI-TN-B7": SI_TN_B7,
    "SI-TN-B8": SI_TN_B8,
    "SI-TN-B9": SI_TN_B9,
    "SI-TN-B10": SI_TN_B10,
    "SI-TN-B11": SI_TN_B11,
    "SI-TN-B12": SI_TN_B12,
    "SI-TN-C1": SI_TN_C1,
    "SI-TN-C2": SI_TN_C2,
    "SI-TN-C3": SI_TN_C3,
    "SI-TN-C4": SI_TN_C4,
    "SI-TN-C5": SI_TN_C5,
    "SI-TN-C6": SI_TN_C6,
    "SI-TN-C7": SI_TN_C7,
    "SI-TN-C8": SI_TN_C8,
    "SI-TN-C9": SI_TN_C9,
    "SI-TN-C10": SI_TN_C10,
    "SI-TN-C11": SI_TN_C11,
    "SI-TN-C12": SI_TN_C12,
    "SI-TN-D1": SI_TN_D1,
    "SI-TN-D2": SI_TN_D2,
    "SI-TN-D3": SI_TN_D3,
    "SI-TN-D4": SI_TN_D4,
    "SI-TN-D5": SI_TN_D5,
    "SI-TN-D6": SI_TN_D6,
    "SI-TN-D7": SI_TN_D7,
    "SI-TN-D8": SI_TN_D8,
    "SI-TN-D9": SI_TN_D9,
    "SI-TN-D10": SI_TN_D10,
    "SI-TN-D11": SI_TN_D11,
    "SI-TN-D12": SI_TN_D12,
    "SI-TN-E1": SI_TN_E1,
    "SI-TN-E2": SI_TN_E2,
    "SI-TN-E3": SI_TN_E3,
    "SI-TN-E4": SI_TN_E4,
    "SI-TN-E5": SI_TN_E5,
    "SI-TN-E6": SI_TN_E6,
    "SI-TN-E7": SI_TN_E7,
    "SI-TN-E8": SI_TN_E8,
    "SI-TN-E9": SI_TN_E9,
    "SI-TN-E10": SI_TN_E10,
    "SI-TN-E11": SI_TN_E11,
    "SI-TN-E12": SI_TN_E12,
    "SI-TN-F1": SI_TN_F1,
    "SI-TN-F2": SI_TN_F2,
    "SI-TN-F3": SI_TN_F3,
    "SI-TN-F4": SI_TN_F4,
    "SI-TN-F5": SI_TN_F5,
    "SI-TN-F6": SI_TN_F6,
    "SI-TN-F7": SI_TN_F7,
    "SI-TN-F8": SI_TN_F8,
    "SI-TN-F9": SI_TN_F9,
    "SI-TN-F10": SI_TN_F10,
    "SI-TN-F11": SI_TN_F11,
    "SI-TN-F12": SI_TN_F12,
    "SI-TN-G1": SI_TN_G1,
    "SI-TN-G2": SI_TN_G2,
    "SI-TN-G3": SI_TN_G3,
    "SI-TN-G4": SI_TN_G4,
    "SI-TN-G5": SI_TN_G5,
    "SI-TN-G6": SI_TN_G6,
    "SI-TN-G7": SI_TN_G7,
    "SI-TN-G8": SI_TN_G8,
    "SI-TN-G9": SI_TN_G9,
    "SI-TN-G10": SI_TN_G10,
    "SI-TN-G11": SI_TN_G11,
    "SI-TN-G12": SI_TN_G12,
    "SI-TN-H1": SI_TN_H1,
    "SI-TN-H2": SI_TN_H2,
    "SI-TN-H3": SI_TN_H3,
    "SI-TN-H4": SI_TN_H4,
    "SI-TN-H5": SI_TN_H5,
    "SI-TN-H6": SI_TN_H6,
    "SI-TN-H7": SI_TN_H7,
    "SI-TN-H8": SI_TN_H8,
    "SI-TN-H9": SI_TN_H9,
    "SI-TN-H10": SI_TN_H10,
    "SI-TN-H11": SI_TN_H11,
    "SI-TN-H12": SI_TN_H12,
    "SI-NT-A1": SI_NT_A1,
    "SI-NT-A2": SI_NT_A2,
    "SI-NT-A3": SI_NT_A3,
    "SI-NT-A4": SI_NT_A4,
    "SI-NT-A5": SI_NT_A5,
    "SI-NT-A6": SI_NT_A6,
    "SI-NT-A7": SI_NT_A7,
    "SI-NT-A8": SI_NT_A8,
    "SI-NT-A9": SI_NT_A9,
    "SI-NT-A10": SI_NT_A10,
    "SI-NT-A11": SI_NT_A11,
    "SI-NT-A12": SI_NT_A12,
    "SI-NT-B1": SI_NT_B1,
    "SI-NT-B2": SI_NT_B2,
    "SI-NT-B3": SI_NT_B3,
    "SI-NT-B4": SI_NT_B4,
    "SI-NT-B5": SI_NT_B5,
    "SI-NT-B6": SI_NT_B6,
    "SI-NT-B7": SI_NT_B7,
    "SI-NT-B8": SI_NT_B8,
    "SI-NT-B9": SI_NT_B9,
    "SI-NT-B10": SI_NT_B10,
    "SI-NT-B11": SI_NT_B11,
    "SI-NT-B12": SI_NT_B12,
    "SI-NT-C1": SI_NT_C1,
    "SI-NT-C2": SI_NT_C2,
    "SI-NT-C3": SI_NT_C3,
    "SI-NT-C4": SI_NT_C4,
    "SI-NT-C5": SI_NT_C5,
    "SI-NT-C6": SI_NT_C6,
    "SI-NT-C7": SI_NT_C7,
    "SI-NT-C8": SI_NT_C8,
    "SI-NT-C9": SI_NT_C9,
    "SI-NT-C10": SI_NT_C10,
    "SI-NT-C11": SI_NT_C11,
    "SI-NT-C12": SI_NT_C12,
    "SI-NT-D1": SI_NT_D1,
    "SI-NT-D2": SI_NT_D2,
    "SI-NT-D3": SI_NT_D3,
    "SI-NT-D4": SI_NT_D4,
    "SI-NT-D5": SI_NT_D5,
    "SI-NT-D6": SI_NT_D6,
    "SI-NT-D7": SI_NT_D7,
    "SI-NT-D8": SI_NT_D8,
    "SI-NT-D9": SI_NT_D9,
    "SI-NT-D10": SI_NT_D10,
    "SI-NT-D11": SI_NT_D11,
    "SI-NT-D12": SI_NT_D12,
    "SI-NT-E1": SI_NT_E1,
    "SI-NT-E2": SI_NT_E2,
    "SI-NT-E3": SI_NT_E3,
    "SI-NT-E4": SI_NT_E4,
    "SI-NT-E5": SI_NT_E5,
    "SI-NT-E6": SI_NT_E6,
    "SI-NT-E7": SI_NT_E7,
    "SI-NT-E8": SI_NT_E8,
    "SI-NT-E9": SI_NT_E9,
    "SI-NT-E10": SI_NT_E10,
    "SI-NT-E11": SI_NT_E11,
    "SI-NT-E12": SI_NT_E12,
    "SI-NT-F1": SI_NT_F1,
    "SI-NT-F2": SI_NT_F2,
    "SI-NT-F3": SI_NT_F3,
    "SI-NT-F4": SI_NT_F4,
    "SI-NT-F5": SI_NT_F5,
    "SI-NT-F6": SI_NT_F6,
    "SI-NT-F7": SI_NT_F7,
    "SI-NT-F8": SI_NT_F8,
    "SI-NT-F9": SI_NT_F9,
    "SI-NT-F10": SI_NT_F10,
    "SI-NT-F11": SI_NT_F11,
    "SI-NT-F12": SI_NT_F12,
    "SI-NT-G1": SI_NT_G1,
    "SI-NT-G2": SI_NT_G2,
    "SI-NT-G3": SI_NT_G3,
    "SI-NT-G4": SI_NT_G4,
    "SI-NT-G5": SI_NT_G5,
    "SI-NT-G6": SI_NT_G6,
    "SI-NT-G7": SI_NT_G7,
    "SI-NT-G8": SI_NT_G8,
    "SI-NT-G9": SI_NT_G9,
    "SI-NT-G10": SI_NT_G10,
    "SI-NT-G11": SI_NT_G11,
    "SI-NT-G12": SI_NT_G12,
    "SI-NT-H1": SI_NT_H1,
    "SI-NT-H2": SI_NT_H2,
    "SI-NT-H3": SI_NT_H3,
    "SI-NT-H4": SI_NT_H4,
    "SI-NT-H5": SI_NT_H5,
    "SI-NT-H6": SI_NT_H6,
    "SI-NT-H7": SI_NT_H7,
    "SI-NT-H8": SI_NT_H8,
    "SI-NT-H9": SI_NT_H9,
    "SI-NT-H10": SI_NT_H10,
    "SI-NT-H11": SI_NT_H11,
    "SI-NT-H12": SI_NT_H12,
    "SI-NN-A1": SI_NN_A1,
    "SI-NN-A2": SI_NN_A2,
    "SI-NN-A3": SI_NN_A3,
    "SI-NN-A4": SI_NN_A4,
    "SI-NN-A5": SI_NN_A5,
    "SI-NN-A6": SI_NN_A6,
    "SI-NN-A7": SI_NN_A7,
    "SI-NN-A8": SI_NN_A8,
    "SI-NN-A9": SI_NN_A9,
    "SI-NN-A10": SI_NN_A10,
    "SI-NN-A11": SI_NN_A11,
    "SI-NN-A12": SI_NN_A12,
    "SI-NN-B1": SI_NN_B1,
    "SI-NN-B2": SI_NN_B2,
    "SI-NN-B3": SI_NN_B3,
    "SI-NN-B4": SI_NN_B4,
    "SI-NN-B5": SI_NN_B5,
    "SI-NN-B6": SI_NN_B6,
    "SI-NN-B7": SI_NN_B7,
    "SI-NN-B8": SI_NN_B8,
    "SI-NN-B9": SI_NN_B9,
    "SI-NN-B10": SI_NN_B10,
    "SI-NN-B11": SI_NN_B11,
    "SI-NN-B12": SI_NN_B12,
    "SI-NN-C1": SI_NN_C1,
    "SI-NN-C2": SI_NN_C2,
    "SI-NN-C3": SI_NN_C3,
    "SI-NN-C4": SI_NN_C4,
    "SI-NN-C5": SI_NN_C5,
    "SI-NN-C6": SI_NN_C6,
    "SI-NN-C7": SI_NN_C7,
    "SI-NN-C8": SI_NN_C8,
    "SI-NN-C9": SI_NN_C9,
    "SI-NN-C10": SI_NN_C10,
    "SI-NN-C11": SI_NN_C11,
    "SI-NN-C12": SI_NN_C12,
    "SI-NN-D1": SI_NN_D1,
    "SI-NN-D2": SI_NN_D2,
    "SI-NN-D3": SI_NN_D3,
    "SI-NN-D4": SI_NN_D4,
    "SI-NN-D5": SI_NN_D5,
    "SI-NN-D6": SI_NN_D6,
    "SI-NN-D7": SI_NN_D7,
    "SI-NN-D8": SI_NN_D8,
    "SI-NN-D9": SI_NN_D9,
    "SI-NN-D10": SI_NN_D10,
    "SI-NN-D11": SI_NN_D11,
    "SI-NN-D12": SI_NN_D12,
    "SI-NN-E1": SI_NN_E1,
    "SI-NN-E2": SI_NN_E2,
    "SI-NN-E3": SI_NN_E3,
    "SI-NN-E4": SI_NN_E4,
    "SI-NN-E5": SI_NN_E5,
    "SI-NN-E6": SI_NN_E6,
    "SI-NN-E7": SI_NN_E7,
    "SI-NN-E8": SI_NN_E8,
    "SI-NN-E9": SI_NN_E9,
    "SI-NN-E10": SI_NN_E10,
    "SI-NN-E11": SI_NN_E11,
    "SI-NN-E12": SI_NN_E12,
    "SI-NN-F1": SI_NN_F1,
    "SI-NN-F2": SI_NN_F2,
    "SI-NN-F3": SI_NN_F3,
    "SI-NN-F4": SI_NN_F4,
    "SI-NN-F5": SI_NN_F5,
    "SI-NN-F6": SI_NN_F6,
    "SI-NN-F7": SI_NN_F7,
    "SI-NN-F8": SI_NN_F8,
    "SI-NN-F9": SI_NN_F9,
    "SI-NN-F10": SI_NN_F10,
    "SI-NN-F11": SI_NN_F11,
    "SI-NN-F12": SI_NN_F12,
    "SI-NN-G1": SI_NN_G1,
    "SI-NN-G2": SI_NN_G2,
    "SI-NN-G3": SI_NN_G3,
    "SI-NN-G4": SI_NN_G4,
    "SI-NN-G5": SI_NN_G5,
    "SI-NN-G6": SI_NN_G6,
    "SI-NN-G7": SI_NN_G7,
    "SI-NN-G8": SI_NN_G8,
    "SI-NN-G9": SI_NN_G9,
    "SI-NN-G10": SI_NN_G10,
    "SI-NN-G11": SI_NN_G11,
    "SI-NN-G12": SI_NN_G12,
    "SI-NN-H1": SI_NN_H1,
    "SI-NN-H2": SI_NN_H2,
    "SI-NN-H3": SI_NN_H3,
    "SI-NN-H4": SI_NN_H4,
    "SI-NN-H5": SI_NN_H5,
    "SI-NN-H6": SI_NN_H6,
    "SI-NN-H7": SI_NN_H7,
    "SI-NN-H8": SI_NN_H8,
    "SI-NN-H9": SI_NN_H9,
    "SI-NN-H10": SI_NN_H10,
    "SI-NN-H11": SI_NN_H11,
    "SI-NN-H12": SI_NN_H12,
    "SI-TS-A1": SI_TS_A1,
    "SI-TS-A2": SI_TS_A2,
    "SI-TS-A3": SI_TS_A3,
    "SI-TS-A4": SI_TS_A4,
    "SI-TS-A5": SI_TS_A5,
    "SI-TS-A6": SI_TS_A6,
    "SI-TS-A7": SI_TS_A7,
    "SI-TS-A8": SI_TS_A8,
    "SI-TS-A9": SI_TS_A9,
    "SI-TS-A10": SI_TS_A10,
    "SI-TS-A11": SI_TS_A11,
    "SI-TS-A12": SI_TS_A12,
    "SI-TS-B1": SI_TS_B1,
    "SI-TS-B2": SI_TS_B2,
    "SI-TS-B3": SI_TS_B3,
    "SI-TS-B4": SI_TS_B4,
    "SI-TS-B5": SI_TS_B5,
    "SI-TS-B6": SI_TS_B6,
    "SI-TS-B7": SI_TS_B7,
    "SI-TS-B8": SI_TS_B8,
    "SI-TS-B9": SI_TS_B9,
    "SI-TS-B10": SI_TS_B10,
    "SI-TS-B11": SI_TS_B11,
    "SI-TS-B12": SI_TS_B12,
    "SI-TS-C1": SI_TS_C1,
    "SI-TS-C2": SI_TS_C2,
    "SI-TS-C3": SI_TS_C3,
    "SI-TS-C4": SI_TS_C4,
    "SI-TS-C5": SI_TS_C5,
    "SI-TS-C6": SI_TS_C6,
    "SI-TS-C7": SI_TS_C7,
    "SI-TS-C8": SI_TS_C8,
    "SI-TS-C9": SI_TS_C9,
    "SI-TS-C10": SI_TS_C10,
    "SI-TS-C11": SI_TS_C11,
    "SI-TS-C12": SI_TS_C12,
    "SI-TS-D1": SI_TS_D1,
    "SI-TS-D2": SI_TS_D2,
    "SI-TS-D3": SI_TS_D3,
    "SI-TS-D4": SI_TS_D4,
    "SI-TS-D5": SI_TS_D5,
    "SI-TS-D6": SI_TS_D6,
    "SI-TS-D7": SI_TS_D7,
    "SI-TS-D8": SI_TS_D8,
    "SI-TS-D9": SI_TS_D9,
    "SI-TS-D10": SI_TS_D10,
    "SI-TS-D11": SI_TS_D11,
    "SI-TS-D12": SI_TS_D12,
    "SI-TS-E1": SI_TS_E1,
    "SI-TS-E2": SI_TS_E2,
    "SI-TS-E3": SI_TS_E3,
    "SI-TS-E4": SI_TS_E4,
    "SI-TS-E5": SI_TS_E5,
    "SI-TS-E6": SI_TS_E6,
    "SI-TS-E7": SI_TS_E7,
    "SI-TS-E8": SI_TS_E8,
    "SI-TS-E9": SI_TS_E9,
    "SI-TS-E10": SI_TS_E10,
    "SI-TS-E11": SI_TS_E11,
    "SI-TS-E12": SI_TS_E12,
    "SI-TS-F1": SI_TS_F1,
    "SI-TS-F2": SI_TS_F2,
    "SI-TS-F3": SI_TS_F3,
    "SI-TS-F4": SI_TS_F4,
    "SI-TS-F5": SI_TS_F5,
    "SI-TS-F6": SI_TS_F6,
    "SI-TS-F7": SI_TS_F7,
    "SI-TS-F8": SI_TS_F8,
    "SI-TS-F9": SI_TS_F9,
    "SI-TS-F10": SI_TS_F10,
    "SI-TS-F11": SI_TS_F11,
    "SI-TS-F12": SI_TS_F12,
    "SI-TS-G1": SI_TS_G1,
    "SI-TS-G2": SI_TS_G2,
    "SI-TS-G3": SI_TS_G3,
    "SI-TS-G4": SI_TS_G4,
    "SI-TS-G5": SI_TS_G5,
    "SI-TS-G6": SI_TS_G6,
    "SI-TS-G7": SI_TS_G7,
    "SI-TS-G8": SI_TS_G8,
    "SI-TS-G9": SI_TS_G9,
    "SI-TS-G10": SI_TS_G10,
    "SI-TS-G11": SI_TS_G11,
    "SI-TS-G12": SI_TS_G12,
    "SI-TS-H1": SI_TS_H1,
    "SI-TS-H2": SI_TS_H2,
    "SI-TS-H3": SI_TS_H3,
    "SI-TS-H4": SI_TS_H4,
    "SI-TS-H5": SI_TS_H5,
    "SI-TS-H6": SI_TS_H6,
    "SI-TS-H7": SI_TS_H7,
    "SI-TS-H8": SI_TS_H8,
    "SI-TS-H9": SI_TS_H9,
    "SI-TS-H10": SI_TS_H10,
    "SI-TS-H11": SI_TS_H11,
    "SI-TS-H12": SI_TS_H12,
    # NEB #E7874; A1 - A6 wells
    "SI-NEB7874-A1": SI_NEB7874_A1,
    "SI-NEB7874-B1": SI_NEB7874_B1,
    "SI-NEB7874-C1": SI_NEB7874_C1,
    "SI-NEB7874-D1": SI_NEB7874_D1,
    "SI-NEB7874-E1": SI_NEB7874_E1,
    "SI-NEB7874-F1": SI_NEB7874_F1,
    "SI-NEB7874-G1": SI_NEB7874_G1,
    "SI-NEB7874-H1": SI_NEB7874_H1,
    "SI-NEB7874-A2": SI_NEB7874_A2,
    "SI-NEB7874-B2": SI_NEB7874_B2,
    "SI-NEB7874-C2": SI_NEB7874_C2,
    "SI-NEB7874-D2": SI_NEB7874_D2,
    "SI-NEB7874-E2": SI_NEB7874_E2,
    "SI-NEB7874-F2": SI_NEB7874_F2,
    "SI-NEB7874-G2": SI_NEB7874_G2,
    "SI-NEB7874-H2": SI_NEB7874_H2,
    "SI-NEB7874-A3": SI_NEB7874_A3,
    "SI-NEB7874-B3": SI_NEB7874_B3,
    "SI-NEB7874-C3": SI_NEB7874_C3,
    "SI-NEB7874-D3": SI_NEB7874_D3,
    "SI-NEB7874-E3": SI_NEB7874_E3,
    "SI-NEB7874-F3": SI_NEB7874_F3,
    "SI-NEB7874-G3": SI_NEB7874_G3,
    "SI-NEB7874-H3": SI_NEB7874_H3,
    "SI-NEB7874-A4": SI_NEB7874_A4,
    "SI-NEB7874-B4": SI_NEB7874_B4,
    "SI-NEB7874-C4": SI_NEB7874_C4,
    "SI-NEB7874-D4": SI_NEB7874_D4,
    "SI-NEB7874-E4": SI_NEB7874_E4,
    "SI-NEB7874-F4": SI_NEB7874_F4,
    "SI-NEB7874-G4": SI_NEB7874_G4,
    "SI-NEB7874-H4": SI_NEB7874_H4,
    "SI-NEB7874-A5": SI_NEB7874_A5,
    "SI-NEB7874-B5": SI_NEB7874_B5,
    "SI-NEB7874-C5": SI_NEB7874_C5,
    "SI-NEB7874-D5": SI_NEB7874_D5,
    "SI-NEB7874-E5": SI_NEB7874_E5,
    "SI-NEB7874-F5": SI_NEB7874_F5,
    "SI-NEB7874-G5": SI_NEB7874_G5,
    "SI-NEB7874-H5": SI_NEB7874_H5,
    "SI-NEB7874-A6": SI_NEB7874_A6,
    "SI-NEB7874-B6": SI_NEB7874_B6,
    "SI-NEB7874-C6": SI_NEB7874_C6,
    "SI-NEB7874-D6": SI_NEB7874_D6,
    "SI-NEB7874-E6": SI_NEB7874_E6,
    "SI-NEB7874-F6": SI_NEB7874_F6,
    "SI-NEB7874-G6": SI_NEB7874_G6,
    "SI-NEB7874-H6": SI_NEB7874_H6,
}

# Chromium lot-specific oligos
CHROMIUM_LOT1_PART_A = [
    "AGAGCGA",
    "CGATTGA",
    "TAGACCA",
    "AAATGCC",
    "CTTTGCG",
    "TCAGCAA",
    "CTCCTAG",
    "ATTATCC",
]
CHROMIUM_LOT2_PART_A = [
    "GACACTA",
    "CCCTCTC",
    "ATCGCGG",
    "CTGGCAG",
    "CCAGCTT",
    "CATAGCA",
    "CGTGTTC",
    "GCACCAG",
]
CHROMIUM_LOT3_PART_A = [
    "ATGTGAC",
    "GACGTCG",
    "ACTGGCG",
    "TGGCAAT",
    "GAGGGTA",
    "GTTTCGC",
    "CAAGTGT",
    "TTGAAGC",
]
CHROMIUM_LOT4_PART_A = [
    "CGATCCT",
    "TGTTGCC",
    "ACCTATT",
    "ACAACTG",
    "CTGTGTC",
    "CTGGAAT",
    "CAGAGTT",
    "GGGCTGT",
]
CHROMIUM_LOT5_PART_A = [
    "TAGCTCC",
    "CAATTTC",
    "GCTCGAG",
    "GAAGGCA",
    "CGGCATG",
    "TATTCCA",
    "TCTCTGG",
    "AGGTACT",
]
CHROMIUM_LOT6_PART_A = [
    "ACTTGCC",
    "GTGAGTT",
    "GTTGTCC",
    "CATAACG",
    "TCGTAAG",
    "TTATCCA",
    "GTGGAGA",
    "TCCTGCA",
]
CHROMIUM_LOT7_PART_A = [
    "TAAGCCA",
    "TCGGTGG",
    "AAGGTAA",
    "GGAACAG",
    "GTGGAAG",
    "TTAGACG",
    "ATCCTAT",
    "TTCCGTG",
]
CHROMIUM_LOT8_PART_A = [
    "GGTTTAG",
    "CGTATAG",
    "ATAGGCT",
    "CTCTCGA",
    "GTCTTAT",
    "GATTGCA",
    "TGAGCTA",
    "ACGCGTG",
]
CHROMIUM_LOT9_PART_A = [
    "CGACACG",
    "TCTCGTG",
    "TGATGAC",
    "TGCGTAA",
    "TACCCTG",
    "AGGTGCC",
    "CTTGTGC",
    "GCATGGC",
]
CHROMIUM_LOT10_PART_A = [
    "CAGCACG",
    "CATGATG",
    "ATCAACG",
    "GATAAGA",
    "CTGGTTC",
    "CGATTCC",
    "AGGTGAG",
    "GGCCTGA",
]
CHROMIUM_LOT11_PART_A = [
    "ACAGTTG",
    "TAAGCAC",
    "ATCTTTG",
    "TCTTGCG",
    "TACATGG",
    "CAAGGTT",
    "AGGCTGC",
    "GGTCGTG",
]
CHROMIUM_LOT12_PART_A = [
    "CCATTAT",
    "GTTGCGG",
    "AGGGTAG",
    "GCCCAAG",
    "TGTGCCT",
    "ATTCTTG",
    "GGTGCCA",
    "GTATAGC",
]
CHROMIUM_LOT13_PART_A = [
    "GGCATCG",
    "GACTGAT",
    "TGGTGTA",
    "TCCGTTG",
    "CCTTCAG",
    "CAGGCCA",
    "GCACCGA",
    "AGATCCA",
]

CHROMIUM_LOT_MAP = {
    "Chromium Lot 1": CHROMIUM_LOT1_PART_A,
    "Chromium Lot 2": CHROMIUM_LOT2_PART_A,
    "Chromium Lot 3": CHROMIUM_LOT3_PART_A,
    "Chromium Lot 4": CHROMIUM_LOT4_PART_A,
    "Chromium Lot 5": CHROMIUM_LOT5_PART_A,
    "Chromium Lot 6": CHROMIUM_LOT6_PART_A,
    "Chromium Lot 7": CHROMIUM_LOT7_PART_A,
    "Chromium Lot 8": CHROMIUM_LOT8_PART_A,
    "Chromium Lot 9": CHROMIUM_LOT9_PART_A,
    "Chromium Lot 10": CHROMIUM_LOT10_PART_A,
    "Chromium Lot 11": CHROMIUM_LOT11_PART_A,
    "Chromium Lot 12": CHROMIUM_LOT12_PART_A,
    "Chromium Lot 13": CHROMIUM_LOT13_PART_A,
}

# GemCode lot-specific oligos
# note: lots 1-15 all use the same part As
GEMCODE_LOT1_PART_A = [
    "GGGTGA",
    "TTCATC",
    "CACAAC",
    "GAAGAT",
    "CAGCAT",
    "CGTCAA",
    "GAAACA",
    "TGTTTC",
]
GEMCODE_LOT16_PART_A = [
    "CAAGTC",
    "ACAAAG",
    "CTGGAT",
    "TTGTCT",
    "AGCCTA",
    "GGGAAC",
    "TTCCTA",
    "CCGTAA",
]
GEMCODE_LOT17_PART_A = [
    "AGTCCA",
    "CAGGAG",
    "CAATGC",
    "CAATCG",
    "AACAGA",
    "TTACTC",
    "ACTGAC",
    "TAAGCC",
]
GEMCODE_LOT18_PART_A = [
    "GCATGT",
    "CCAACA",
    "TCGGTA",
    "ATCGTG",
    "ATTCTC",
    "CGTTAG",
    "TTCACT",
    "GGTTTG",
]
GEMCODE_LOT19_PART_A = [
    "CTTTCA",
    "TTGTTC",
    "TAGCCA",
    "GCGTAT",
    "CGTACA",
    "CCTTCG",
    "CACACA",
    "TACTTC",
]
GEMCODE_LOT20_PART_A = [
    "CTTCAT",
    "ATTCCT",
    "GTCTCC",
    "CAGGGA",
    "ATCCGA",
    "CGAATC",
    "AAACCC",
    "CGCTAA",
]
GEMCODE_LOT21_PART_A = [
    "CAGATC",
    "AATCCG",
    "TACGTG",
    "GAACAA",
    "AGAGCG",
    "CCAGAT",
    "CGCTTC",
    "TTATCC",
]

GEMCODE_LOT_MAP = {
    "GemCode Lots 1-15": GEMCODE_LOT1_PART_A,
    "GemCode Lot 16": GEMCODE_LOT16_PART_A,
    "GemCode Lot 17": GEMCODE_LOT17_PART_A,
    "GemCode Lot 18": GEMCODE_LOT18_PART_A,
    "GemCode Lot 19": GEMCODE_LOT19_PART_A,
    "GemCode Lot 20": GEMCODE_LOT20_PART_A,
    "GemCode Lot 21": GEMCODE_LOT21_PART_A,
}

# if a whitelist isn't in this map, then assume it doesn't contain the alts and don't try to do lot detection
WHITELIST_TO_LOT_MAP = {
    "884K-november-2015": GEMCODE_LOT_MAP,
    "4M-with-alts-february-2016": CHROMIUM_LOT_MAP,
}
